// This file is generated

P_name_0 = [
"Adergas 5, Adergas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Adergas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Beli potok  1, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Besnica 10, Besnica, Ljubljana, Slovenija",
"Besnica, Ljubljana, Slovenija",
"Bezen\u0161kovo Bukovje, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Bolni\u0161nica Celje, Ipav\u010deva 10, Celje, Celje, Slovenska \u0160tajerska, Slovenija",
"Bolni\u0161nica doktorja Petra Dr\u017eaja, Vodnikova 62, Ljubljana, Ljubljana, Slovenija",
"Brezova 25, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezova 26, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezovo 18, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Budimpe\u0161ta, Mad\u017earska",
"Bukovlje 8, Bukovlje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Bukovlje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Celje, Celje, Slovenska \u0160tajerska, Slovenija",
"Celje, Slovenska \u0160tajerska, Slovenija",
"Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Cerklje na Gorenjskem, Gorenjska, Slovenija",
"\u010cre\u0161kova, Vojnik, Slovenska \u0160tajerska, Slovenija",
"\u010cretve\u017e 8, \u010cretve\u017e, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"\u010cretve\u017e, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Dachau - tabori\u0161\u010de, Nem\u010dija",
"Doberdob, Gorica, Slovenija",
"Dobrava 7",
"Dobrava pri Konjicah, Slovenske Konjice, Slovenska \u0160tajerska, Slovenija",
"Dobrova 4, Slovenska \u0160tajerska, Slovenija",
"Dol 13, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Dol 14, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Dol 7, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Dol pod Gojko 15, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Dolenjska, Slovenija",
"Doli\u010d, Mislinja, Koro\u0161ka, Slovenija",
"Dresden, Nem\u010dija",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Gorenja vas pri Polici 4, Gorenja vas pri Polici, Grosuplje, Dolenjska, Slovenija",
"Gorenja vas pri Polici, Grosuplje, Dolenjska, Slovenija",
"Gorenjska, Slovenija",
"Gorica, Slovenija",
"Gornja Sava 16, Kranj, Kranj, Gorenjska, Slovenija",
"Gri\u017ee, \u017dalec, Slovenska \u0160tajerska, Slovenija",
"Grosuplje, Dolenjska, Slovenija",
"Italija",
"Javor 3, Javor, Ljubljana, Slovenija",
"Javor 6, Javor, Ljubljana, Slovenija",
"Javor, Ljubljana, Slovenija",
"Kamnik, Gorenjska, Slovenija",
"Kijev, Ukrajina",
"klinika Golnik, Kranj, Gorenjska, Slovenija",
"Komenda, Gorenjska, Slovenija",
"Koro\u0161ka, Slovenija",
"Ko\u0161ke Poljane 1, Ko\u0161ke Poljane, \u0160martno pri Litiji, Dolenjska, Slovenija",
"Ko\u0161ke Poljane, \u0160martno pri Litiji, Dolenjska, Slovenija",
"Kozjak 55, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 57, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 64, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 65, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kranj, Gorenjska, Slovenija",
"Kranj, Gorenjska, Slovenija",
"Kranj, Kranj, Gorenjska, Slovenija",
"Lani\u0161e 3, Lani\u0161e, Tunjice, Kamnik, Gorenjska, Slovenija",
"Lani\u0161e 4, Lani\u0161e, Tunjice, Kamnik, Gorenjska, Slovenija",
"Lani\u0161e, Tunjice, Kamnik, Gorenjska, Slovenija",
"Lindek 17, Lindek, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Lindek 3, Lindek, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Lindek, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Lipa 1, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Lipa 10, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Lipa 24, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Lipa 9, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Ljubljana, Ljubljana, Slovenija",
"Ljubljana, Ljubljana, Slovenija",
"Ljubljana, Slovenija",
"Mad\u017earska",
"Maribor, Maribor, Slovenska \u0160tajerska, Slovenija",
"Maribor, Slovenska \u0160tajerska, Slovenija",
"Medvode, Gorenjska, Slovenija",
"Mislinja, Koro\u0161ka, Slovenija",
"Mislinja, Mislinja, Koro\u0161ka, Slovenija",
"Morav\u010de, Gorenjska, Slovenija",
"Morav\u010de, Morav\u010de, Gorenjska, Slovenija",
"Naklo, Gorenjska, Slovenija",
"Nem\u010dija",
"Nova Cerkev, Slovenska \u0160tajerska, Slovenija",
"Nova Dobrava 54, Slovenska \u0160tajerska, Slovenija",
"Nova Dobrava 57, Slovenska \u0160tajerska, Slovenija",
"Ogorevc, \u0160tore, Slovenska \u0160tajerska, Slovenija",
"Paka pri Velenju, Velenje, Slovenska \u0160tajerska, Slovenija",
"pokopali\u0161\u010de Frankolovo, Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Polica 2, Naklo, Gorenjska, Slovenija",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 25, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 28, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Pol\u017ee 16, Pol\u017ee, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Pol\u017ee, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Povodje 2, Povodje, Vodice, Gorenjska, Slovenija",
"Povodje, Vodice, Gorenjska, Slovenija",
"Prevalje, Koro\u0161ka, Slovenija",
"Primskovo 17, Kranj, Kranj, Gorenjska, Slovenija",
"Ravne pri \u0160o\u0161tanju, \u0160o\u0161tanj, Slovenska \u0160tajerska, Slovenija",
"Repnje 18 (Koblanc), Repnje, Vodice, Gorenjska, Slovenija",
"Repnje, Vodice, Gorenjska, Slovenija",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Ro\u017eni vrh 9, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Runtole 2, Runtole, Celje, Slovenska \u0160tajerska, Slovenija",
"Runtole 6, Runtole, Celje, Slovenska \u0160tajerska, Slovenija",
"Runtole, Celje, Slovenska \u0160tajerska, Slovenija",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 4, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selo pri Pancah 7, Selo pri Pancah, Ljubljana, Slovenija",
"Selo pri Pancah, Ljubljana, Slovenija",
"Skomarje 13, Skomarje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Skomarje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Slovenija",
"Slovenska \u0160tajerska, Slovenija",
"Slovenske Konjice, Slovenska \u0160tajerska, Slovenija",
"Socka, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Splitska 36, Velenje, Velenje, Slovenska \u0160tajerska, Slovenija",
"Sti\u0161ka vas 18, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Sti\u0161ka vas 5, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Sti\u0161ka vas 7, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Sti\u0161ka vas 8, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Stranice 13, Stranice, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Stranice 8, Stranice, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Stranice, Slovenska \u0160tajerska, Slovenija",
"Stranice, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Stra\u017ea 13, Stra\u017ea, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Stra\u017ea, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Stra\u017eica 5, Slovenska \u0160tajerska, Slovenija",
"Strmen, Slovenska \u0160tajerska, Slovenija",
"Suhadole, Komenda, Gorenjska, Slovenija",
"\u0160martno pri Litiji, Dolenjska, Slovenija",
"\u0160martno v Ro\u017eni Dolini, Slovenska \u0160tajerska, Slovenija",
"\u0160o\u0161tanj, Slovenska \u0160tajerska, Slovenija",
"\u0160o\u0161tanj, \u0160o\u0161tanj, Slovenska \u0160tajerska, Slovenija",
"\u0160t. Ilj pod Turjakom, Slovenska \u0160tajerska, Slovenija",
"\u0160tefanja Gora 26, \u0160tefanja Gora, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"\u0160tefanja Gora, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"\u0160tore, Slovenska \u0160tajerska, Slovenija",
"\u0160tore, \u0160tore, Slovenska \u0160tajerska, Slovenija",
"Trnovlje 1, Trnovlje pri Socki, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Trnovlje pri Socki 19, Trnovlje pri Socki, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Trnovlje pri Socki, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Tro\u0161\u010dine 6, Tro\u0161\u010dine, Grosuplje, Dolenjska, Slovenija",
"Tro\u0161\u010dine, Grosuplje, Dolenjska, Slovenija",
"Tuji Grm 14, Tuji Grm, Ljubljana, Slovenija",
"Tuji Grm, Ljubljana, Slovenija",
"Tunjice, Gorenjska, Slovenija",
"Tunjice, Kamnik, Gorenjska, Slovenija",
"Ukrajina",
"Velenje, Slovenska \u0160tajerska, Slovenija",
"Velenje, Velenje, Slovenska \u0160tajerska, Slovenija",
"Velesovo, Gorenjska, Slovenija",
"Velika \u0160tanga 51, Velika \u0160tanga, \u0160martno pri Litiji, Dolenjska, Slovenija",
"Velika \u0160tanga, \u0160martno pri Litiji, Dolenjska, Slovenija",
"Verpete 20, Verpete, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Verpete, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Vesca 9, Vesca, Vodice, Gorenjska, Slovenija",
"Vesca, Vodice, Gorenjska, Slovenija",
"Vitanje, Slovenska \u0160tajerska, Slovenija",
"Vizore 12, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Vizore 5, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Vnajnarje 1, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 19, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 7, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 8, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje, Ljubljana, Slovenija",
"Vodice, Gorenjska, Slovenija",
"Vodice, Gorenjska, Slovenija",
"Vojnik, Slovenska \u0160tajerska, Slovenija",
"Vojnik, Slovenska \u0160tajerska, Slovenija",
"Vojnik, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Volavlje 13, Volavlje, Ljubljana, Slovenija",
"Volavlje 14a, Volavlje, Ljubljana, Slovenija",
"Volavlje 16, Volavlje, Ljubljana, Slovenija",
"Volavlje 22, Volavlje, Ljubljana, Slovenija",
"Volavlje, Ljubljana, Slovenija",
"Zbiljsko jezero, Medvode, Gorenjska, Slovenija",
"Zlate\u010de 10, Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Zre\u010de, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"\u017dale, Ljubljana, Ljubljana, Slovenija",
"\u017dalec, Slovenska \u0160tajerska, Slovenija",
"\u017dalec, \u017dalec, Slovenska \u0160tajerska, Slovenija"
]
Dwr.ScriptLoaded('dwr_db_P_name_0.js');
