// This file is generated

I_birth_place_0 = [
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Trnovlje pri Socki 19, Trnovlje pri Socki, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Volavlje 13, Volavlje, Ljubljana, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Repnje 18 (Koblanc), Repnje, Vodice, Gorenjska, Slovenija",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Bukovlje 8, Bukovlje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"",
"\u010cretve\u017e 8, \u010cretve\u017e, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Bukovlje 8, Bukovlje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"Pol\u017ee 16, Pol\u017ee, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"Trnovlje pri Socki 19, Trnovlje pri Socki, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Dol pod Gojko 15, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Dol pod Gojko 15, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Dol pod Gojko 15, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Lani\u0161e 3, Lani\u0161e, Tunjice, Kamnik, Gorenjska, Slovenija",
"Sti\u0161ka vas 7, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Javor 3, Javor, Ljubljana, Slovenija",
"",
"Javor 6, Javor, Ljubljana, Slovenija",
"Javor 6, Javor, Ljubljana, Slovenija",
"Javor 6, Javor, Ljubljana, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Zlate\u010de 10, Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Besnica 10, Besnica, Ljubljana, Slovenija",
"Besnica 10, Besnica, Ljubljana, Slovenija",
"",
"",
"Volavlje 16, Volavlje, Ljubljana, Slovenija",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"",
"",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 8, Vnajnarje, Ljubljana, Slovenija",
"",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 16, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 1, Vnajnarje, Ljubljana, Slovenija",
"",
"",
"",
"",
"Gorenja vas pri Polici 4, Gorenja vas pri Polici, Grosuplje, Dolenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Brezovo 18, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezovo 18, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezovo 18, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sti\u0161ka vas 18, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Sti\u0161ka vas 7, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Polica 2, Naklo, Gorenjska, Slovenija",
"Sti\u0161ka vas 18, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"",
"Sti\u0161ka vas 18, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Lani\u0161e 4, Lani\u0161e, Tunjice, Kamnik, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vnajnarje 7, Vnajnarje, Ljubljana, Slovenija",
"Vnajnarje 1, Vnajnarje, Ljubljana, Slovenija",
"",
"Tuji Grm 14, Tuji Grm, Ljubljana, Slovenija",
"",
"",
"",
"Ko\u0161ke Poljane 1, Ko\u0161ke Poljane, \u0160martno pri Litiji, Dolenjska, Slovenija",
"",
"",
"Stranice 8, Stranice, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"Stranice 8, Stranice, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Bukovlje 8, Bukovlje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Stranice 8, Stranice, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Lipa 9, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Velenje, Velenje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"Dobrova 4, Slovenska \u0160tajerska, Slovenija",
"Bukovlje 8, Bukovlje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Trnovlje 1, Trnovlje pri Socki, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Volavlje 13, Volavlje, Ljubljana, Slovenija",
"Volavlje 13, Volavlje, Ljubljana, Slovenija",
"",
"Javor 3, Javor, Ljubljana, Slovenija",
"Velika \u0160tanga 51, Velika \u0160tanga, \u0160martno pri Litiji, Dolenjska, Slovenija",
"",
"Volavlje 13, Volavlje, Ljubljana, Slovenija",
"Volavlje 22, Volavlje, Ljubljana, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Zlate\u010de 10, Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"\u010cre\u0161kova, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Zlate\u010de 10, Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Zlate\u010de 10, Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"Zlate\u010de 10, Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"Brezova 26, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezova 26, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"\u0160o\u0161tanj, \u0160o\u0161tanj, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Repnje 18 (Koblanc), Repnje, Vodice, Gorenjska, Slovenija",
"Repnje 18 (Koblanc), Repnje, Vodice, Gorenjska, Slovenija",
"",
"Polje 28, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"Repnje 18 (Koblanc), Repnje, Vodice, Gorenjska, Slovenija",
"",
"Stra\u017ea 13, Stra\u017ea, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lipa 10, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Volavlje 16, Volavlje, Ljubljana, Slovenija",
"Volavlje 16, Volavlje, Ljubljana, Slovenija",
"",
"",
"Volavlje, Ljubljana, Slovenija",
"Volavlje 14a, Volavlje, Ljubljana, Slovenija",
"Selo pri Pancah 7, Selo pri Pancah, Ljubljana, Slovenija",
"Volavlje 16, Volavlje, Ljubljana, Slovenija",
"",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Prevalje, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"Slovenija",
"Slovenija",
"",
"",
"",
"",
"",
"",
"",
"Runtole 6, Runtole, Celje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Morav\u010de, Morav\u010de, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vizore 12, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Vizore 5, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Stra\u017eica 5, Slovenska \u0160tajerska, Slovenija",
"Vizore 5, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Vizore 5, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Vizore 5, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"Vizore 5, Vizore, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"Brezova 25, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Polje 28, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Vesca 9, Vesca, Vodice, Gorenjska, Slovenija",
"",
"",
"",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Polje 28, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Polje 25, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 28, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Verpete 20, Verpete, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Polje 28, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Brezova 25, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Ro\u017eni Vrh 16, Ro\u017eni Vrh, Celje, Slovenska \u0160tajerska, Slovenija",
"Kozjak 64, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"Paka pri Velenju, Velenje, Slovenska \u0160tajerska, Slovenija",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"Beli potok 2, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"Skomarje 13, Skomarje, Zre\u010de, Slovenska \u0160tajerska, Slovenija",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"Lipa 9, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"Kozjak 55, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Nova Cerkev, Slovenska \u0160tajerska, Slovenija",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"Dobrava 7",
"",
"Kozjak 64, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Lipa 9, Lipa pri Frankolovem, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"Paka pri Velenju, Velenje, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"Kozjak 80, Kozjak, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Volavlje 22, Volavlje, Ljubljana, Slovenija",
"",
"",
"",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"Zlate\u010de 10, Zlate\u010de, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Frankolovo, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Dol pod Gojko 15, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok  1, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Selce 4, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Selce 3, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"Bezen\u0161kovo Bukovje, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"Selce 6, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sti\u0161ka vas 18, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"Gornja Sava 16, Kranj, Kranj, Gorenjska, Slovenija",
"",
"Slovenija",
"Adergas 5, Adergas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"Adergas 5, Adergas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"",
"Primskovo 17, Kranj, Kranj, Gorenjska, Slovenija",
"Primskovo 17, Kranj, Kranj, Gorenjska, Slovenija",
"",
"",
"",
"Adergas 5, Adergas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"",
"",
"\u0160tefanja Gora 26, \u0160tefanja Gora, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Mislinja, Mislinja, Koro\u0161ka, Slovenija",
"",
"",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Runtole 2, Runtole, Celje, Slovenska \u0160tajerska, Slovenija",
"Dol 7, Dol pod Gojko, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"Runtole 6, Runtole, Celje, Slovenska \u0160tajerska, Slovenija",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Brezova 25, Brezova, Celje, Slovenska \u0160tajerska, Slovenija",
"Runtole 6, Runtole, Celje, Slovenska \u0160tajerska, Slovenija",
"Lindek 3, Lindek, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"Beli potok 8, Beli potok, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Gorenja vas pri Polici 4, Gorenja vas pri Polici, Grosuplje, Dolenjska, Slovenija",
"",
"",
"Tro\u0161\u010dine 6, Tro\u0161\u010dine, Grosuplje, Dolenjska, Slovenija",
"",
"",
"Sti\u0161ka vas 5, Sti\u0161ka vas, Cerklje na Gorenjskem, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"Selce 2, Selce, Vojnik, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ogorevc, \u0160tore, Slovenska \u0160tajerska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"Polje 15, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"",
"Vodice, Gorenjska, Slovenija",
"",
"",
"",
"Suhadole, Komenda, Gorenjska, Slovenija",
"Suhadole, Komenda, Gorenjska, Slovenija",
"",
"",
"Vodice, Gorenjska, Slovenija",
"Povodje 2, Povodje, Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"Vodice, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vodice, Gorenjska, Slovenija",
"",
"",
"",
"",
"Vodice, Gorenjska, Slovenija",
"Polje 19, Polje pri Vodicah, Vodice, Gorenjska, Slovenija",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
