// This file is generated

F_name_0 = [
"Family of Jo\u017ee and Kristina Pritekelj",
"Family of Karli",
"Family of Ljudmila",
"Family of Marjana",
"Family of Matija and Rozalija Zalo\u017enik",
"Family of Mitja and Lilijana Sel\u010dan",
"Family of Marko Ahlin and Breda Ahlin",
"Family of Bla\u017e Ahtik and Agnes Ahtik",
"Family of Sebastijan Ahtik and Marija Steble",
"Family of Jorg Alber and Simona Alber",
"Family of Franci Albreht and Anica Albreht",
"Family of Ivan Alja\u017e and Terezija Alja\u017e",
"Family of Jurij Apalik and Agnes Apalik",
"Family of Anton A\u0161kerc and Helena Stren\u010dan",
"Family of Andrej Blazin\u0161ek and Apolonija Blazin\u0161ek",
"Family of Anton Blazin\u0161ek and Ur\u0161ula Blazin\u0161ek",
"Family of Janez Blazin\u0161ek and Jo\u017eefa Blazin\u0161ek",
"Family of Daniel Bla\u017ein\u010di\u010d and Lilijana",
"Family of Martin Bogina and Agata Bogina",
"Family of Drago Borkovi\u010d and Florjana Podjavor\u0161ek",
"Family of Emil Borovnik and Fran\u010di\u0161ka Borovnik",
"Family of Fran\u010di\u0161ka Borovnik",
"Family of Henrik Borovnik and Katarina Borovnik",
"Family of Jernej Borovnik and Magdalena Cizel",
"Family of Martin Borovnik and Fran\u010di\u0161ka Mavser",
"Family of Valentin Borovnik and Vida Racman",
"Family of Vincenc Borovnik and Anica Ba\u010dnik",
"Family of Anton Bratun",
"Family of \u0160tefan Bratun and Agnes Bratun",
"Family of Andrej Brodnik",
"Family of Vinko Brodnik and Rozika Brodnik",
"Family of Franc Brun\u010dek and Ivana Brun\u010dek",
"Family of Borut Buri\u010d and Lucija Buri\u010d Kebli\u010d",
"Family of Zdenka Clare",
"Family of Janez Debevec and Marija Debevec",
"Family of Sebastijan Debevec and Agnes Debevec",
"Family of Branko Del\u010dnjak and Marija Del\u010dnjak",
"Family of Ivan Del\u010dnjak and Ana Del\u010dnjak",
"Family of Ivan Divjak and Til\u010dka Divjak",
"Family of Toma\u017e Dobnikar and Melita Dobnikar",
"Family of Jo\u017ee Dolin\u0161ek and Julijana Dolin\u0161ek",
"Family of Stanko Dolin\u0161ek and Martina Dolin\u0161ek",
"Family of Gizela Dru\u017eanovi\u010d",
"Family of Jo\u017eef Er\u0161aj and Barbara Er\u0161aj",
"Family of Bla\u017e Fijav\u017e and Lucija Krajnc",
"Family of Franc Fijav\u017e and Marija Fijav\u017e",
"Family of Ga\u0161per Fijav\u017e and Elizabeta Kovk",
"Family of Zvone Gaj\u0161ek and Danica Podjavor\u0161ek",
"Family of Branko Gobec",
"Family of Jakob Gobec and Marija Gobec",
"Family of Miroslav Gobec",
"Family of Vlado Gobec",
"Family of Anton Goren\u0161ek and Ur\u0161ula Goren\u0161ek",
"Family of Jakob Goren\u0161ek and Helena Petre",
"Family of Valentin Goren\u0161ek and Agata Goren\u0161ek",
"Family of Ivana Gr\u010dar",
"Family of Ivan Grilc and Helena Grilc",
"Family of Jurij Grilc and Katarina Grilc",
"Family of Ivan Grm and Angela Lu\u017enik Grm",
"Family of Bernardka Groblar",
"Family of Jo\u017ee Groblar and Bernardka Groblar",
"Family of Roman Guzelj and Sonja Guzelj",
"Family of Andrej Habi\u010d and Magdalena Habi\u010d",
"Family of Margareta Habi\u010d",
"Family of Matija Habi\u010d and Gertruda Habi\u010d",
"Family of Mihael Habi\u010d and Ur\u0161ula Habi\u010d",
"Family of Martin Heinke and Andreja Heinke",
"Family of Anton Hren and Marija Podjavor\u0161ek",
"Family of Marija Hren",
"Family of Ga\u0161per Ir\u0161i\u010d and Elizabeta Ir\u0161i\u010d",
"Family of Matija Iskra\u010d and Angela Iskra\u010d",
"Family of Bojan Jagodi\u010d",
"Family of Karel Jagodi\u010d and Terezija Jagodi\u010d",
"Family of Lenika Jagodi\u010d",
"Family of Poldi Jagodi\u010d",
"Family of Rajko Jagodi\u010d and Cvetka Jagodi\u010d",
"Family of Stanko Jagodi\u010d",
"Family of \u0160tefan Jagodi\u010d",
"Family of Zlatka Jagodi\u010d",
"Family of Andrej Jan\u010dar and Marija Jan\u010dar",
"Family of Anton Jan\u010dar and Ana Jan\u010dar",
"Family of Anton Jan\u010dar and Marija Jan\u010dar",
"Family of Anton Jan\u010dar and Ur\u0161ula Jan\u010dar",
"Family of Franc Jan\u010dar and Apolonija Jan\u010dar",
"Family of Franc Jan\u010dar and Marija Jan\u010dar",
"Family of Janez Jan\u010dar and Gertruda Jan\u010dar",
"Family of Janez Jan\u010dar and Helena Jan\u010dar",
"Family of Anton Javnikar and Marija Javnikar",
"Family of Marko Jenko and Nata\u0161a Jenko",
"Family of Matija Jerinc",
"Family of Jovan and Marija Jovan",
"Family of Ivan Jug and Miroslava Jug",
"Family of Vekoslav Jurina and Romana Jurina",
"Family of Jakob Juvan",
"Family of Mirko Juvan and Marta Juvan",
"Family of Boris Kadunc and Sa\u0161a Kadunc",
"Family of Romana Kadunc",
"Family of Anton Kav\u0161ek",
"Family of Jakob Kerhne and Ne\u017ea Kerhne",
"Family of Klappencker and Gabrijela Kraiss",
"Family of \u0160tefan Klopotan and Dragica Klopotan",
"Family of Ivan Koglar and Marija Koglar",
"Family of Matev\u017e Koglar and Doroteja Koglar",
"Family of Matev\u017e Koglar and Marija Koglar",
"Family of Matija Koglar and Ne\u017ea Koglar",
"Family of Jurij Kokalj and Elizabeta Kokalj",
"Family of Anton Kon\u010dar and Fran\u010di\u0161ka Kon\u010dar",
"Family of Franc Kon\u010dar and Antonija Kon\u010dar",
"Family of Janez Kon\u010dar and Agnes Kon\u010dar",
"Family of Janez Kon\u010dar and Marija Kon\u010dar",
"Family of Jurij Kon\u010dar and Agnes Kon\u010dar",
"Family of Matija Kon\u010dar and Elizabeta Kon\u010dar",
"Family of Anton Koro\u0161ec and Jo\u017eefa Koro\u0161ec",
"Family of Jo\u017ee Koro\u0161ec and Betka Podjavor\u0161ek",
"Family of Jo\u017eef Koro\u0161ec and Kunigunda Koro\u0161ec",
"Family of Rozalija Koro\u0161ec",
"Family of Urban Koro\u0161ec and Katarina Koro\u0161ec",
"Family of Valentin Koro\u0161ec and Marija Koro\u0161ec",
"Family of Anton Kos",
"Family of Boris Kos",
"Family of Marija Kos",
"Family of Jo\u017ee Ko\u0161ir and Metka Ko\u0161ir",
"Family of Peter Ko\u0161ir and Marija Kova\u010d",
"Family of Johan Kotnik and Angela Kotnik",
"Family of Martin Kotnik and Marija Kova\u010d",
"Family of Matija Kotnik and Marija Kotnik",
"Family of Peter Kotnik and Helena Podjavor\u0161ek",
"Family of Fran\u010di\u0161ek Kova\u010d and Angela Kova\u010d",
"Family of Ivan Kova\u010d and Kata Jozanovi\u0107",
"Family of Ivan Kova\u010d and Marija Poto\u010dnik",
"Family of Jo\u017eef Kova\u010d and Margareta Kova\u010d",
"Family of Janez Kozel and Elizabeta Kozel",
"Family of Jo\u017ee Ko\u017eelj and Majda Ko\u017eelj",
"Family of Horst Kraiss and Jo\u017eica Kraiss",
"Family of Tomas Kraiss and Vera Kraiss",
"Family of Jakob Krajan and Agnes Krajan",
"Family of Ivan Krajan\u0161i\u010d and Katarina Podgor\u0161ek",
"Family of Klara Krajnc",
"Family of Matev\u017e Krajnc and Helena/Marija Krajnc",
"Family of Lenart Kralji\u010d and Elizabeta Kralji\u010d",
"Family of Jo\u017ee Kranjc and Ivana Mezgec",
"Family of Jakob Kremenek",
"Family of Andrej Kreuh and Jerneja Podjavor\u0161ek",
"Family of \u0160tefan Krnjav\u0161ek and Gretica Verani\u010d",
"Family of Zlatko Krnjav\u0161ek",
"Family of Tone Kuder and Slavica Kuder",
"Family of Andrej Kumer and Jo\u017eica Kumer",
"Family of Jo\u017eica Kumer",
"Family of Andrej Lampret and Marija Lampret",
"Family of Gregor Lavri\u010d and Marta Lavri\u010d",
"Family of Ale\u0161 Laznik and Darja Laznik",
"Family of Bo\u017eidar Laznik and Jelka Laznik",
"Family of Edi Laznik and Marija Laznik",
"Family of Matja\u017e Laznik and Elizabeta Laznik",
"Family of Anton Ljubi\u010d and Gertruda Ljubi\u010d",
"Family of Anton Ljubi\u010d and Terezija Ljubi\u010d",
"Family of Bernard Ljubi\u010d and Marija Ljubi\u010d",
"Family of Marko Ljubi\u010d and Fran\u010di\u0161ka Ljubi\u010d",
"Family of Darja Lu\u017enik",
"Family of Slavko Lu\u017enik and Angela Lu\u017enik Grm",
"Family of Slavko Lu\u017enik and Angela Lu\u017enik Grm",
"Family of Marija Malgaj",
"Family of Zlatko Malgaj",
"Family of Anton Marn and Elizabeta Marn",
"Family of Jo\u017eef Marn and Ne\u017ea Marn",
"Family of Alojz Marov\u0161ek",
"Family of Alojz Marov\u0161ek and Cecilija Marov\u0161ek",
"Family of Anica Marov\u0161ek",
"Family of Cilka Marov\u0161ek",
"Family of Franci Marov\u0161ek",
"Family of Ivan Marov\u0161ek",
"Family of Ivan Marov\u0161ek and Marija Marov\u0161ek",
"Family of Marica Marov\u0161ek",
"Family of Valentin Marov\u0161ek",
"Family of Leon Matalen and Tanja \u0160tuhec",
"Family of Marjan Matalen and Tanja \u0160tuhec",
"Family of Simon Mayer and Marija Mayer",
"Family of Miha Meh",
"Family of Miha Meh and Ne\u017ea Meh",
"Family of Ivan Mencin and Terezija Mencin",
"Family of Ciril Mencinger and Antonija Mencinger \u017debovec",
"Family of Zvonko Mencinger and Vikica Mencinger",
"Family of Bo\u017eidar Mertelj and Miranda Pestar Mertelj",
"Family of Ivan Miklav and Sofija Miklav",
"Family of Radivoj Mohori\u010d and Andreja Mohori\u010d",
"Family of Martin Morek and Margareta \u0160anti\u017e",
"Family of Thomas Moritz and Daniela Moritz",
"Family of Anton Mrak and Marija Mrak",
"Family of Bla\u017e Mrak and Marjana Mrak",
"Family of Jakob Mrak",
"Family of Matev\u017e Mrak and Jera Mrak",
"Family of Ivanka Muzelj",
"Family of Ivan Nogra\u0161ek and Ana Nogra\u0161ek",
"Family of Martin Novak and Cathrin Novak",
"Family of Martin Novak and Terezija Novak",
"Family of Simon Novak and Claudia Novak",
"Family of Tone Novak and Cilka Novak",
"Family of Andrej Omahen and Helena Omahen",
"Family of Anton Omahen and Margareta Omahen",
"Family of Lavrencij Omahen and Elizabeta Omahen",
"Family of Mihael Omahen and Marija Omahen",
"Family of Anton Opr\u010dkal and Pavlina Pinter",
"Family of Janez Osel and Jera \u017debovec",
"Family of Janez Pader and Terezija Sel\u010dan",
"Family of Anton Palfi and Terezija Palfi",
"Family of Silvo Parovel and Ne\u017eika Parovel",
"Family of Marjan Pav\u010di\u010d and Martina Pav\u010di\u010d",
"Family of Franci Pavli\u010d and Anica Zorko",
"Family of Leopold Pavli\u010d and Ana \u0160travs",
"Family of Pe\u010dnik and Matilda Pe\u010dnik",
"Family of Andrej Pe\u010dnik and Marija Kova\u010d",
"Family of Drago Pestar and Mojca \u0160enk",
"Family of Valentin Pestar and Marija Sirc",
"Family of Anton Petelin\u0161ek and Ana Marija Kukovec",
"Family of Anton Petelin\u0161ek and Vesna Petelin\u0161ek",
"Family of Oto Petelin\u0161ek and Mira Petelin\u0161ek",
"Family of Matija Petre and Rozalija Sel\u010dan",
"Family of \u0160tefan Petre and Jul\u010dka Petre",
"Family of Ignac Petrej and Helena Petre",
"Family of Rudolf Petrej and Marija Petre",
"Family of Rudolf Petrej and Marija Petrej",
"Family of Andrej Pinter and Agata Pinter",
"Family of Andrej Pinter and Marjana Pinter",
"Family of Franc Pinter and Agnes Pinter",
"Family of Fran\u010di\u0161ek Pinter and Alojzija Pinter",
"Family of Fran\u010di\u0161ek Pinter and Katarina Pinter",
"Family of Fran\u010di\u0161ek Pinter and Marija Pinter",
"Family of Gregor Pinter and Marija Pinter",
"Family of Jakob Pinter and Antonija Pinter",
"Family of Jo\u017eef Pinter and \u0160tefanija Pinter",
"Family of Martin Pinter and Katarina Pinter",
"Family of Anton Pirnat and Katarina Pirnat",
"Family of Bartlomej Planinc and Gertruda Steble",
"Family of Ana Podgor\u0161ek",
"Family of Franc Podgor\u0161ek and Marija Podgor\u0161ek",
"Family of Franc Podgor\u0161ek and Marija Podgor\u0161ek",
"Family of Jakob Podgor\u0161ek and Ne\u017ea Podgor\u0161ek",
"Family of Jo\u017eef Podgor\u0161ek",
"Family of Jo\u017eef Podgor\u0161ek and Elizabeta Podgor\u0161ek",
"Family of Luka Podgor\u0161ek and Elizabeta Podgor\u0161ek",
"Family of Luka Podgor\u0161ek and Jera Podgor\u0161ek",
"Family of Marija Podgor\u0161ek",
"Family of Matev\u017e Podgor\u0161ek and Marija Podgor\u0161ek",
"Family of Matija Podgor\u0161ek and Fran\u010di\u0161ka Koro\u0161ec",
"Family of Pavel Podgor\u0161ek and Mica Podgor\u0161ek",
"Family of Simon Podgor\u0161ek and Marija Podgor\u0161ek",
"Family of Aleksander Podjavor\u0161ek",
"Family of Alojz Podjavor\u0161ek and Marta Podjavor\u0161ek",
"Family of Andrej Podjavor\u0161ek and Andreja Podjavor\u0161ek",
"Family of Anton Podjavor\u0161ek and Ana Podjavor\u0161ek",
"Family of Anton Podjavor\u0161ek and Marjana Podjavor\u0161ek",
"Family of Anton Podjavor\u0161ek and Matilda Podjavor\u0161ek",
"Family of Boris Podjavor\u0161ek and Lidija Buri\u010d",
"Family of Cilka Podjavor\u0161ek",
"Family of Dominik Podjavor\u0161ek and Angela Podjavor\u0161ek",
"Family of Florjan Podjavor\u0161ek and Mira Podjavor\u0161ek",
"Family of Fran\u010di\u0161ek Podjavor\u0161ek and Helena Podjavor\u0161ek",
"Family of Janez Podjavor\u0161ek and Bisera Medjedovi\u010d",
"Family of Janez Podjavor\u0161ek and Marija Podjavor\u0161ek",
"Family of Jo\u017eef Podjavor\u0161ek and Agnes Podjavor\u0161ek",
"Family of Jo\u017eef Podjavor\u0161ek and Helena Podjavor\u0161ek",
"Family of Karel Podjavor\u0161ek",
"Family of Konrad Podjavor\u0161ek",
"Family of Ludvik Podjavor\u0161ek",
"Family of Ludvik Podjavor\u0161ek and An\u010dka Podjavor\u0161ek",
"Family of Marko Podjavor\u0161ek and Nina Sobotkiewicz",
"Family of Matej Podjavor\u0161ek and Lili Djaki\u010d",
"Family of Matev\u017e Podjavor\u0161ek and Marija Podjavor\u0161ek",
"Family of Matev\u017e Podjavor\u0161ek and Marija Podjavor\u0161ek",
"Family of Matja\u017e Podjavor\u0161ek and Natalija Podjavor\u0161ek",
"Family of Mihael Podjavor\u0161ek and Lucija Podjavor\u0161ek",
"Family of Mihael Podjavor\u0161ek and Rozalija Podjavor\u0161ek",
"Family of Peter Podjavor\u0161ek and Tinka Retko",
"Family of Primo\u017e Podjavor\u0161ek and Darja Podjavor\u0161ek",
"Family of Slavko Podjavor\u0161ek and Erna Podjavor\u0161ek",
"Family of Urban Podjavor\u0161ek",
"Family of Valentin Podjavor\u0161ek and Ivanka Podjavor\u0161ek",
"Family of Jo\u017ee Podjed and Zofija Podjed",
"Family of Matja\u017e Podjed and Tanja Podjed",
"Family of Bogdan Podvornik and Meta Kolar",
"Family of Franc Podvornik and Slavica Kuder",
"Family of Martin Polen\u0161ek and Terezija Novak",
"Family of Mihael Poto\u010dnik and Terezija Novak",
"Family of Florjan Preklet and Marijana Preklet",
"Family of Alojzija Prezelj",
"Family of Alojzija Prezelj",
"Family of Alojz Pritekelj and Vida Pritekelj",
"Family of Jo\u017ee Pungartnik and Katarina Pungartnik",
"Family of Toma\u017e Pungartnik and Jo\u017eica Pungartnik",
"Family of Lenart Ram\u0161ak and Marija Ram\u0161ak",
"Family of Ciril Ravnak and Genovefa Sel\u010dan",
"Family of Ivo Razdev\u0161ek and Martina Podjavor\u0161ek",
"Family of Horst Rischert and Gabrijela Kraiss",
"Family of Ivan Selan and Margareta Selan",
"Family of Jo\u017eef Selan and Marija Selan",
"Family of Aleksander Sel\u010dan and Livija Jeler\u010di\u010d",
"Family of Andrej Sel\u010dan and Milena Kumperger",
"Family of Anton Sel\u010dan and Ivanka Sel\u010dan",
"Family of Branko Sel\u010dan",
"Family of Du\u0161an Sel\u010dan and Irena Sel\u010dan",
"Family of Franc Sel\u010dan and Mimica Krnjav\u0161ek",
"Family of Franc Sel\u010dan and Alojzija Sel\u010dan",
"Family of Franc Sel\u010dan and Marija Sel\u010dan",
"Family of Franc Sel\u010dan and Fanika Zevnik",
"Family of Franci Sel\u010dan and Erika \u017daler",
"Family of Gregor Sel\u010dan and Marija Sel\u010dan",
"Family of Ignac Sel\u010dan and Angela Mlakar",
"Family of Jo\u017ee Sel\u010dan and Slavica Sel\u010dan",
"Family of Jo\u017ee Sel\u010dan and Zinka Sel\u010dan",
"Family of Jo\u017eef Sel\u010dan and Rozalija Sel\u010dan",
"Family of Jurij Sel\u010dan and Marija Sel\u010dan",
"Family of Jurij Sel\u010dan and Terezija Sel\u010dan",
"Family of Jurij Sel\u010dan and Ur\u0161ula Sel\u010dan",
"Family of Jurij Sel\u010dan and Helena Stren\u010dan",
"Family of Jurij Sel\u010dan and Julijana \u0160krlin",
"Family of Jurij Rudolf Sel\u010dan",
"Family of Karel Sel\u010dan and Anica Sel\u010dan",
"Family of Karel Sel\u010dan and Karlina Sel\u010dan",
"Family of Karli Sel\u010dan and Danica Majcen",
"Family of Majda Sel\u010dan",
"Family of Martin Sel\u010dan and Cveta Sel\u010dan",
"Family of Matija Sel\u010dan and Marija Sel\u010dan",
"Family of Matija Sel\u010dan and Marija Sel\u010dan",
"Family of Mihael Sel\u010dan and Marija Sel\u010dan",
"Family of Milan Sel\u010dan and Jo\u017eica \u0160tefani\u010d",
"Family of Oskar Sel\u010dan",
"Family of Peter Sel\u010dan and Janja Hudomalj",
"Family of Peter Sel\u010dan and Silva Jezernik",
"Family of Peter Sel\u010dan and Fanika Sel\u010dan",
"Family of Roman Sel\u010dan",
"Family of Simon Sel\u010dan and Marija Sel\u010dan",
"Family of Slavko Sel\u010dan and Zofka Sel\u010dan",
"Family of Tatjana Sel\u010dan",
"Family of Vinko Sel\u010dan and Marija Bogataj",
"Family of Zlatka Sel\u010dan",
"Family of Franci Sirc and Milka Sirc",
"Family of Franci Sirc and Nancy Luisa Sirc",
"Family of Janez Sirc and Angela Sirc",
"Family of Janez Sirc and Marjana Sirc",
"Family of Jo\u017ee Sirc and Anica Sirc",
"Family of Jo\u017eef Sirc and Gertruda Sirc",
"Family of Jo\u017eef Sirc and Marija Sirc",
"Family of Jurij Sirc and Marija Sirc",
"Family of Miran Sirc and Simona Sirc",
"Family of Silvester Sirc and Veronika Sirc",
"Family of Vinko Sirc and Metka Fajfar",
"Family of Andrej Skrt and Antonija Krivec",
"Family of Zvonko Skrt and Marija Skrt",
"Family of Jo\u017ee Sovi\u010d and Marija Podjavor\u0161ek",
"Family of Bla\u017e Steble and Marija Steble",
"Family of Janez Steble and Marija Steble",
"Family of Matev\u017e Steble and Marija Steble",
"Family of Mihael Steble and Elizabeta Steble",
"Family of Sebastijan Steble and Elizabeta Steble",
"Family of Edvard Stepihar and Katarina Stepihar",
"Family of Klemen Stropnik and Zvonka Stropnik",
"Family of Marija Strus",
"Family of Peter \u0160afran and Jo\u017eefa \u0160afran",
"Family of Jakob \u0160ircelj and Jera \u0160ircelj",
"Family of Mihael \u0160ircelj and Margareta \u0160ircelj",
"Family of Jakob \u0160kerjanc and Barbara \u0160kerjanc",
"Family of Ivan \u0160majc and Albina \u0160majc",
"Family of Ivo \u0160majc and Irena \u0160majc",
"Family of Matja\u017e \u0160majc and Sandra \u0160majc",
"Family of Silvester \u0160pegel and Ljudmila \u0160pegel",
"Family of Luka \u0160tirn and Marija \u0160tirn",
"Family of Izidor \u0160tular and Margareta \u0160tular",
"Family of Tone Tolazzi and Mateja Tolazzi",
"Family of Jurij Torinek and Ana Torinek",
"Family of Anton Ude and Katarina Ude",
"Family of Matev\u017e Urbinc and Marija Urbinc",
"Family of Milan Vampelj and Barbara Vampelj",
"Family of Mihael Vetter and Aleksandra Kraiss",
"Family of Leopold Vocovnik and Angela Turn\u0161ek",
"Family of Leopold Vocovnik and Marija Vocovnik",
"Family of Milan Vre\u010dek and Darja Vre\u010dek",
"Family of Simon Vri\u0161er and Ana Vri\u0161er",
"Family of Franc Vrta\u010dnik and Mina Vrta\u010dnik",
"Family of Martin Wokau and Marija Wokau",
"Family of Matija Zalo\u017enik and Johana Zalo\u017enik",
"Family of Elio Zgrinski\u0107 and Marija Podjavor\u0161ek",
"Family of Alojz Zorko and Alma Kranjc",
"Family of Drago Zorko and Dragica Zorko",
"Family of Ivan Zorko and Irena Zorko",
"Family of Ivan Zorko and Marija Zorko",
"Family of Jo\u017eef Zorko and Marija Bevc",
"Family of Lovrenc Zupan and Marija Zupan",
"Family of Anton \u017debovec",
"Family of Branko \u017debovec and Darja \u017debovec",
"Family of Ciril \u017debovec and Antonija Mencinger \u017debovec",
"Family of Ciril \u017debovec and Antonija \u017debovec",
"Family of Ciril \u017debovec and Marjeta \u017debovec",
"Family of Feliks \u017debovec and Veronika \u017debovec",
"Family of Franc \u017debovec and Fran\u010di\u0161ka \u017debovec",
"Family of Fran\u010di\u0161ek \u017debovec and Marinka \u017debovec",
"Family of Gregor \u017debovec and Marija \u017debovec",
"Family of Iztok \u017debovec and Mihelina \u017debovec",
"Family of Janez \u017debovec",
"Family of Jurij \u017debovec and Jera \u017debovec",
"Family of Miran \u017debovec and Anica \u017debovec",
"Family of Rajko \u017debovec and Jana \u017debovec",
"Family of Valentin \u017debovec and Agnes \u017debovec",
"Family of Valentin \u017debovec and Ur\u0161ula \u017debovec",
"Family of Vande \u017dgajnar and Monika \u017dgajnar",
"Family of Jakob \u017dirovnik and Marija \u017dirovnik",
"Family of Ga\u0161per \u017dnider and Ur\u0161ula \u017dnider"
]
Dwr.ScriptLoaded('dwr_db_F_name_0.js');
