// This file is generated

C_text_0 = [
"<p>\n<b>\nDate: \n</b>\n17 Sep 1943\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1829\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1942 and 1996\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1921\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1902\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1829\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\n7 Jun 1924\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1997\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\n1997\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1902\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1902\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1921\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1884\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1947 and 2014\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1967 and 2012\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1989 and 2019\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1951 and 1997\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\n1966\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\n2004\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nLow\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1966 and 1980\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1946 and 1987\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1971 and 1990\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\n1967\n</p><p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1911 and 1998\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1984 and 2013\n</p><p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\n1\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nPage: \n</b>\n1\n</p>",
"<p>\n<b>\nDate: \n</b>\n1989\n</p><p>\n<b>\nPage: \n</b>\n1. zapis\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n13 Aug 1905\n</p><p>\n<b>\nPage: \n</b>\n102\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n4 May 1959\n</p><p>\n<b>\nPage: \n</b>\n2\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 Apr 1959\n</p><p>\n<b>\nPage: \n</b>\n2\n</p>",
"<p>\n<b>\nDate: \n</b>\nafter 1852\n</p><p>\n<b>\nPage: \n</b>\n2; Polje 33 - Podgor\u0161ek - Spodni Pipan\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n2000\n</p><p>\n<b>\nPage: \n</b>\n2. zapis\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n4 May 1959\n</p><p>\n<b>\nPage: \n</b>\n3\n</p>",
"<p>\n<b>\nDate: \n</b>\n30 Apr 1959\n</p><p>\n<b>\nPage: \n</b>\n3\n</p>",
"<p>\n<b>\nDate: \n</b>\n1999\n</p><p>\n<b>\nPage: \n</b>\n3. zapis\n</p>",
"<p>\n<b>\nDate: \n</b>\n4 May 1959\n</p><p>\n<b>\nPage: \n</b>\n4\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 Apr 1959\n</p><p>\n<b>\nPage: \n</b>\n4\n</p>",
"<p>\n<b>\nDate: \n</b>\n1933\n</p><p>\n<b>\nPage: \n</b>\n4. zapis\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 May 1959\n</p><p>\n<b>\nPage: \n</b>\n5\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 May 1959\n</p><p>\n<b>\nPage: \n</b>\n5\n</p>",
"<p>\n<b>\nDate: \n</b>\n1956\n</p><p>\n<b>\nPage: \n</b>\n5. zapis\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 May 1959\n</p><p>\n<b>\nPage: \n</b>\n6\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 May 1959\n</p><p>\n<b>\nPage: \n</b>\n6\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 May 1959\n</p><p>\n<b>\nPage: \n</b>\n7\n</p>",
"<p>\n<b>\nDate: \n</b>\n22 Aug 1941\n</p><p>\n<b>\nPage: \n</b>\nDru\u017eina Borovnik - dokument\n</p>",
"<p>\n<b>\nDate: \n</b>\n22 Feb 1892\n</p><p>\n<b>\nPage: \n</b>\nknjiga 8, str. 30\n</p>",
"<p>\n<b>\nDate: \n</b>\nbefore 2006\n</p><p>\n<b>\nPage: \n</b>\nrodovnik na platnicah\n</p>",
"<p>\n<b>\nDate: \n</b>\n5 Sep 1805\n</p><p>\n<b>\nPage: \n</b>\nstr 91, 4. vrstica (krstni zapis Elizabete Vri\u0161er)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n14 Sep 1818\n</p><p>\n<b>\nPage: \n</b>\nstr, 121, 5. vrstica (krstni zapis Matev\u017ea Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n30 Mar 1809\n</p><p>\n<b>\nPage: \n</b>\nstr.  43 (mrli\u0161ki zapis Mihaela Podjavor\u0161ka)\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 May 1837\n</p><p>\n<b>\nPage: \n</b>\nstr.  44, 5. zapis (mrli\u0161ki zapis Jakoba Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Feb 1786\n</p><p>\n<b>\nPage: \n</b>\nstr.  5, 2. zapis (poro\u010dni list )\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n13 Feb 1822\n</p><p>\n<b>\nPage: \n</b>\nstr.  5, 4. zapis (poro\u010dni list Andreja Jan\u010darja in Marije Kokalj)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1807\n</p><p>\n<b>\nPage: \n</b>\nstr.  801 (krstni zapis Simona Sel\u010dana)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 May 1789\n</p><p>\n<b>\nPage: \n</b>\nstr. 1, 2. zapis (poro\u010dni list Matije Habi\u010da)\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 Feb 1865\n</p><p>\n<b>\nPage: \n</b>\nstr. 10\n</p>",
"<p>\n<b>\nDate: \n</b>\n17 Oct 1888\n</p><p>\n<b>\nPage: \n</b>\nstr. 10, 1. zapis (krstni zapis Marije Kova\u010d)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Apr 1894\n</p><p>\n<b>\nPage: \n</b>\nstr. 10, 5. zapis (krstni zapis Jurija Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Feb 1822\n</p><p>\n<b>\nPage: \n</b>\nstr. 10, 7. zapis, krstni zapis Matija Kon\u010darja\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Dec 1848\n</p><p>\n<b>\nPage: \n</b>\nstr. 10, 8. zapis (krstni list Antona Omahna)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n18 Jan 1889\n</p><p>\n<b>\nPage: \n</b>\nstr. 102, 2. zapis (mrli\u0161ki list Janeza Jan\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n7 Feb 1876\n</p><p>\n<b>\nPage: \n</b>\nstr. 102; poro\u010dni zapis Valentina \u017debovca (1850) in Agnes Alja\u017e (ok. 1851)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1832\n</p><p>\n<b>\nPage: \n</b>\nstr. 104 (krstni zapis Jo\u017eefe Fijav\u017e)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n2 May 1914\n</p><p>\n<b>\nPage: \n</b>\nstr. 105, 2. zapis (krsnti list Janeza Jan\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Mar 1846\n</p><p>\n<b>\nPage: \n</b>\nstr. 106, 4. vrstica (krstni zapis Marije Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Mar 1906\n</p><p>\n<b>\nPage: \n</b>\nstr. 106; krstni zapis Angele Pinter (1906)\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Aug 1868\n</p><p>\n<b>\nPage: \n</b>\nstr. 107, 3. zapis (krstni zapis Marije Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n18 Sep 1915\n</p><p>\n<b>\nPage: \n</b>\nstr. 107, 5. vrstica (krstni zapis Fran\u010di\u0161ke Kon\u010dar, r. Brun\u010dek)\n</p><p>\n<b>\nConfidence: \n</b>\nVery High\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Feb 1815\n</p><p>\n<b>\nPage: \n</b>\nstr. 109, 2. zapis (krstni zapis Jo\u017eefa Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1 Sep 1884\n</p><p>\n<b>\nPage: \n</b>\nstr. 11\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 11\n</p>",
"<p>\n<b>\nDate: \n</b>\nbefore 2006\n</p><p>\n<b>\nPage: \n</b>\nstr. 11\n</p>",
"<p>\n<b>\nDate: \n</b>\n1789\n</p><p>\n<b>\nPage: \n</b>\nstr. 11 (poro\u010dni zapis Gregorja Sel\u010dana in Marije Ravnak)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 11 (Selce 6 - Gregor Sel\u010dan, 3 - Simon Sel\u010dan\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Apr 1828\n</p><p>\n<b>\nPage: \n</b>\nstr. 11, 5. zapis (Janez Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Feb 1828\n</p><p>\n<b>\nPage: \n</b>\nstr. 11, 5. zapis (poro\u010dni list Mihaela Omahna in Marije Urbinc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1823 and 1869\n</p><p>\n<b>\nPage: \n</b>\nstr. 11, 6. lastnik (3, Steble Sebastian, Baurn von Bellipotok)\n</p><p>\n<b>\nConfidence: \n</b>\nVery High\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Nov 1786\n</p><p>\n<b>\nPage: \n</b>\nstr. 11, 6. vrstica (krstni zapis Ne\u017ee Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1836\n</p><p>\n<b>\nPage: \n</b>\nstr. 110 (krstni zapis Ivana/Janeza Grilca)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n24 Aug 1834\n</p><p>\n<b>\nPage: \n</b>\nstr. 111, 3. vrstica (krstni zapis Marije Fijav\u017e)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n18 Nov 1918\n</p><p>\n<b>\nPage: \n</b>\nstr. 113, 2. zapis (krstni list Andreja Jan\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n22 Feb 1785\n</p><p>\n<b>\nPage: \n</b>\nstr. 114 (krstni zapis Jo\u017eefa Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1806\n</p><p>\n<b>\nPage: \n</b>\nstr. 114 (krstni zapis Katarine \u0160kerjanc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1835\n</p><p>\n<b>\nPage: \n</b>\nstr. 115 (krstni zapis Marije Koro\u0161ec)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n29 Mar 1899\n</p><p>\n<b>\nPage: \n</b>\nstr. 115, 3. vrstica (krstni zapis Franca Sel\u010dana)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1869\n</p><p>\n<b>\nPage: \n</b>\nstr. 116 (poro\u010dni zapis Antona Koro\u0161ca in Jo\u017eefe Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 12\n</p>",
"<p>\n<b>\nDate: \n</b>\nbefore 2006\n</p><p>\n<b>\nPage: \n</b>\nstr. 12\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 12, 1. lastnik (Bresova 26, Mayer Simon)\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Nov 1828\n</p><p>\n<b>\nPage: \n</b>\nstr. 12, 2. zapis (poro\u010dni list Ivana Sevan in Margarete Apalik)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Aug 1870\n</p><p>\n<b>\nPage: \n</b>\nstr. 121, 2. zapis (rojstni zapis sina Matev\u017ea Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1836\n</p><p>\n<b>\nPage: \n</b>\nstr. 123 (krstni zapis Terezije Fijav\u017e)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1869\n</p><p>\n<b>\nPage: \n</b>\nstr. 125 (krstni zapis Marije Grilc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Oct 1849\n</p><p>\n<b>\nPage: \n</b>\nstr. 127, 2. vrstica (krstni zapis Terezije Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 25 May 1900 and 11 Jun 1900\n</p><p>\n<b>\nPage: \n</b>\nstr. 129 (krst Marije Sel\u010dan, por. Gobec)\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Sep 1830\n</p><p>\n<b>\nPage: \n</b>\nstr. 129, 1. vrstica (krstni zapis Matev\u017ea Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1827\n</p><p>\n<b>\nPage: \n</b>\nstr. 13 (Polle 33, Lukas Podgorscheg, Spoden Pippan)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1830\n</p><p>\n<b>\nPage: \n</b>\nstr. 13 (poroka Luka Podgor\u0161ka in Elizabete Kozel)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n7 Feb 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 13, 1. vrstice (poro\u010dni zapis Sebastijana Ahtika in Marije Krajnc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n20 Mar 1907\n</p><p>\n<b>\nPage: \n</b>\nstr. 130; krstni zapis Jere Debevec\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 19 Aug 1875 and 24 Oct 1875\n</p><p>\n<b>\nPage: \n</b>\nstr. 135, 136 (pogreb mrtvorojene Sel\u010dan)\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Oct 1885\n</p><p>\n<b>\nPage: \n</b>\nstr. 138, 2. zapis (krstni zapis Martina Kotnika)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n15 Nov 1821\n</p><p>\n<b>\nPage: \n</b>\nstr. 139, 5. vrstica (krstni zapis Marije Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n24 Sep 1910\n</p><p>\n<b>\nPage: \n</b>\nstr. 139, 5. zapis (krstni zapis Terezije Pinter)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n30 Apr 1835\n</p><p>\n<b>\nPage: \n</b>\nstr. 139, 8. vrstica (krstni zapis Janeza Stebleta)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 14\n</p>",
"<p>\n<b>\nDate: \n</b>\n15 Nov 1879\n</p><p>\n<b>\nPage: \n</b>\nstr. 14, 6. zapis\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1830\n</p><p>\n<b>\nPage: \n</b>\nstr. 140 (poro\u010dni zapis Simona Sel\u010dana in Marije Stepihar)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1764\n</p><p>\n<b>\nPage: \n</b>\nstr. 141 (krstni zapis Gregorja Sel\u010dana)\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Jan 1839\n</p><p>\n<b>\nPage: \n</b>\nstr. 146 (poro\u010dni zapis Jo\u017eefa Podgor\u0161ka in Elizabete Torinek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n15 Feb 1850\n</p><p>\n<b>\nPage: \n</b>\nstr. 147; krstni zapis Valentina \u017debovca (1850)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1 Oct 1779\n</p><p>\n<b>\nPage: \n</b>\nstr. 148 - 149, 3. (krstni zapis Simona \u017dniderja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n13 Dec 1779\n</p><p>\n<b>\nPage: \n</b>\nstr. 148 - 149, 6. (krstni zapis Marije Kerhne)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n4 Feb 1824\n</p><p>\n<b>\nPage: \n</b>\nstr. 15\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 15\n</p>",
"<p>\n<b>\nDate: \n</b>\nJan 1902\n</p><p>\n<b>\nPage: \n</b>\nstr. 150 (krst Franca Sel\u010dana)\n</p>",
"<p>\n<b>\nDate: \n</b>\n12 Aug 1859\n</p><p>\n<b>\nPage: \n</b>\nstr. 152, 3. zapis (krstni zapis Mihaela Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n6 Feb 1736\n</p><p>\n<b>\nPage: \n</b>\nstr. 153, 2. zapis (poro\u010dni zapis Jo\u017eefa Podjavor\u0161ka in Ne\u017ee Kremen\u0161ek)\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Dec 1863\n</p><p>\n<b>\nPage: \n</b>\nstr. 155, 5. vrstica (mrli\u0161ki zapis Antona Goren\u0161ka)\n</p>",
"<p>\n<b>\nDate: \n</b>\nDec 1836\n</p><p>\n<b>\nPage: \n</b>\nstr. 156\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n15 Jul 1858\n</p><p>\n<b>\nPage: \n</b>\nstr. 156, 4. vrstica (krstni zapis Jakoba Goren\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n4 Sep 1822\n</p><p>\n<b>\nPage: \n</b>\nstr. 157 (poro\u010dni zapis Bla\u017ea Mraka in Marijane Zupan)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 16\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Apr 1820\n</p><p>\n<b>\nPage: \n</b>\nstr. 16, 1. zapis (mrli\u0161ki list Andreja Omahna)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1 Jul 1781\n</p><p>\n<b>\nPage: \n</b>\nstr. 161, 3. (krstni zapis Jakoba Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n2 Mar 1782\n</p><p>\n<b>\nPage: \n</b>\nstr. 164, 2. zapis (krstni zapis Gregorja Kerhneja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1 Feb 1841\n</p><p>\n<b>\nPage: \n</b>\nstr. 166, 1. vrstica (poro\u010dni zapis Matev\u017ea Podgor\u0161ka in Marije Mayer)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Jun 1860\n</p><p>\n<b>\nPage: \n</b>\nstr. 167, 3. vrstica (krstni zapis Alojzije in Ane Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1854\n</p><p>\n<b>\nPage: \n</b>\nstr. 17, 1. zapis (krstni zapis Ale\u0161a Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1847\n</p><p>\n<b>\nPage: \n</b>\nstr. 177 (krstni zapis Antona Koro\u0161ca)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Jan 1898\n</p><p>\n<b>\nPage: \n</b>\nstr. 179 (poro\u010dni zapis Ivana Koglarja in Marije Grilc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 18\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 18\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1823 and 1869\n</p><p>\n<b>\nPage: \n</b>\nstr. 18; Jurij \u017debovec - Polje 22\n</p>",
"<p>\n<b>\nDate: \n</b>\n20 Jan 1893\n</p><p>\n<b>\nPage: \n</b>\nstr. 18; krstni zapis Marije Debevec\n</p>",
"<p>\n<b>\nDate: \n</b>\n3 Feb 1779\n</p><p>\n<b>\nPage: \n</b>\nstr. 18; poro\u010dni zapis Antona Mraka in Marije Juvan\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Feb 1887\n</p><p>\n<b>\nPage: \n</b>\nstr. 181, 1. vrstica (poro\u010dni zapis Franca Pinterja in Alojzije Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Dec 1891\n</p><p>\n<b>\nPage: \n</b>\nstr. 184, 2. vrstica (krstni zapis Antona Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nNov 1880\n</p><p>\n<b>\nPage: \n</b>\nstr. 189; pogrebni zapis Ivane/Jane Sel\u010dan (1873 - 1880)\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Jul 1895\n</p><p>\n<b>\nPage: \n</b>\nstr. 19, 3. zapis (krstni zapis Jakoba Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n12 May 1803\n</p><p>\n<b>\nPage: \n</b>\nstr. 19, 6. zapis (Krstni list Margarete Habi\u010d)\n</p>",
"<p>\n<b>\nDate: \n</b>\n9 Jul 1856\n</p><p>\n<b>\nPage: \n</b>\nstr. 190, 3. zapis (krstni zapis Jakoba Pintarja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 2\n</p>",
"<p>\n<b>\nDate: \n</b>\n1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 2\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 2\n</p>",
"<p>\n<b>\nDate: \n</b>\n30 Jan 1815\n</p><p>\n<b>\nPage: \n</b>\nstr. 2, 2. zapis (poro\u010dni zapis Janeza Kon\u010darja in Agnes Javnikar)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n15 Feb 1830\n</p><p>\n<b>\nPage: \n</b>\nstr. 2, 7. vrstica (poro\u010dni zapis Sebastijana Stebleta in Elizabete Vri\u0161er)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 2, stavba 4 (Rosenberg 12, Podgorscheg Jakob)\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 2, stavbe 18 - 20 (Ro\u00dfenberg 12, Podgorscheg Lukas)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1881\n</p><p>\n<b>\nPage: \n</b>\nstr. 20 (mrli\u0161ki zapis Matev\u017ea Koglarja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n16 Jul 1853\n</p><p>\n<b>\nPage: \n</b>\nstr. 20,  11. zapis (krstni list Margarete Bratun)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1 Feb 1833\n</p><p>\n<b>\nPage: \n</b>\nstr. 20, 4. vrstica (krstni zapis Valentina Goren\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n3 Feb 1783\n</p><p>\n<b>\nPage: \n</b>\nstr. 21; poro\u010dni zapis Janeza Osla in Jere Jerinc\n</p>",
"<p>\n<b>\nDate: \n</b>\n1855\n</p><p>\n<b>\nPage: \n</b>\nstr. 22\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 23\n</p>",
"<p>\n<b>\nDate: \n</b>\n22 Feb 1829\n</p><p>\n<b>\nPage: \n</b>\nstr. 23 (mrli\u0161ki zapis Jere \u017debovec)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n5 Feb 1816\n</p><p>\n<b>\nPage: \n</b>\nstr. 23 (poro\u010dni zapis Jo\u017eefa Podjavor\u0161ka in Helene Poto\u010dnik)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Dec 1799\n</p><p>\n<b>\nPage: \n</b>\nstr. 23, 4. zapis (krstni list Gertrude Wokau)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 24\n</p>",
"<p>\n<b>\nDate: \n</b>\n1870\n</p><p>\n<b>\nPage: \n</b>\nstr. 24 (krstni zapis Marije Koro\u0161ec)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n17 Mar 1747\n</p><p>\n<b>\nPage: \n</b>\nstr. 248 (krstni list Jo\u017eefa Podjavor\u0161ka)\n</p>",
"<p>\n<b>\nDate: \n</b>\nAug 1873\n</p><p>\n<b>\nPage: \n</b>\nstr. 248 (krstni zapis Ivane/Jane Sel\u010dan)\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 25\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Jan 1789\n</p><p>\n<b>\nPage: \n</b>\nstr. 25 (krstni list Marije Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 26\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 26\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Jan 1792\n</p><p>\n<b>\nPage: \n</b>\nstr. 26, 7. zapis (krstni zapis Marije Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Nov 1754\n</p><p>\n<b>\nPage: \n</b>\nstr. 262, 6. zapis (krsnti list Andreja Omahna)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Sep 1750\n</p><p>\n<b>\nPage: \n</b>\nstr. 266 (krstni zapis Mihaela Podjavor\u0161ka)\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 27\n</p>",
"<p>\n<b>\nDate: \n</b>\n16 Sep 1870\n</p><p>\n<b>\nPage: \n</b>\nstr. 27, 3. vrstica (mrli\u0161ki zapis Marije Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n26 Dec 1803\n</p><p>\n<b>\nPage: \n</b>\nstr. 28, 4. zapis (krstni zapis \u0160tefana Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Nov 1891\n</p><p>\n<b>\nPage: \n</b>\nstr. 28, 4. zapis (poro\u010dni zapis Janeza Kon\u010darja in Marije Marn)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 29\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 29\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nstr. 29 (poro\u010dni zapis Ivana Grilca in Helene Nogra\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1829\n</p><p>\n<b>\nPage: \n</b>\nstr. 29 (poro\u010dni zapis Matev\u017ea Koglarja in Marije \u0160kerjanc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n9 Feb 1857\n</p><p>\n<b>\nPage: \n</b>\nstr. 29, 2. izpis (poro\u010dni list Antona Ljubi\u010da in Terezije Selan)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 May 1799\n</p><p>\n<b>\nPage: \n</b>\nstr. 29, 3. zapis (krstni list Ivana Selana)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Jan 1809\n</p><p>\n<b>\nPage: \n</b>\nstr. 29, 6. vrstica (krstni zapis Marije Krajnc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 10 Mar 1957 and 18 Dec 1957\n</p><p>\n<b>\nPage: \n</b>\nstr. 29; 1156, 232, Podjavorsek, Alvert\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 3\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 3\n</p>",
"<p>\n<b>\nDate: \n</b>\n16 May 1793\n</p><p>\n<b>\nPage: \n</b>\nstr. 3,  7.  zapis (krstni zapis Janeza Kon\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n29 Apr 1871\n</p><p>\n<b>\nPage: \n</b>\nstr. 3, 11. zapis (krstni list Antona Jan\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Feb 1789\n</p><p>\n<b>\nPage: \n</b>\nstr. 3, 2. vrstica (poro\u010dni zapis Matev\u017ea Stebleta in Marije \u0160ibanc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 3, stavba 21 (Rosenberg 12, Podgorscheg Jakob)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1846\n</p><p>\n<b>\nPage: \n</b>\nstr. 30 (poro\u010dni zapis Jo\u017eefa Koro\u0161ca in Kunigunde Fijav\u017e)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Jan 1746\n</p><p>\n<b>\nPage: \n</b>\nstr. 30, 6. zapis (poro\u010dni list Lavrencija Omahna in Elizabete Bratun)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Jul 1894\n</p><p>\n<b>\nPage: \n</b>\nstr. 30; krstni zapis Janeza Debevca\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 31\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Feb 1897\n</p><p>\n<b>\nPage: \n</b>\nstr. 31, 3. zapis (krstni zapis Jo\u017eefa Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n16 Feb 1892\n</p><p>\n<b>\nPage: \n</b>\nstr. 318, 4. vrstica (mrli\u0161ki zapis Alojzije Pinter, r. Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n24 Feb 1892\n</p><p>\n<b>\nPage: \n</b>\nstr. 319, 1. vrstica (mrli\u0161ki zapis Antona Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 32\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Nov 1839\n</p><p>\n<b>\nPage: \n</b>\nstr. 32; poro\u010dni zapis Gregorja \u017debovca (1798) in Mice Verta\u010dnik (1819)\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 33\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Nov 1846\n</p><p>\n<b>\nPage: \n</b>\nstr. 33-34, 3. zapis (poro\u010dni list Matija Kon\u010darja in Elizabete Marn)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Dec 1830\n</p><p>\n<b>\nPage: \n</b>\nstr. 33, 3. zapis (krstni list Janeza Jan\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Jan 1801\n</p><p>\n<b>\nPage: \n</b>\nstr. 33, 5. vrstica (poro\u010dni zapis Jakoba Podgor\u0161ka in Ne\u017ee Kugler)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Sep 1807\n</p><p>\n<b>\nPage: \n</b>\nstr. 33, 5. zapis\n</p>",
"<p>\n<b>\nDate: \n</b>\n5 Mar 1803\n</p><p>\n<b>\nPage: \n</b>\nstr. 33b,  13. vrstica (krstni list Antona Ljubi\u010da)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 34\n</p>",
"<p>\n<b>\nDate: \n</b>\n24 Dec 1774\n</p><p>\n<b>\nPage: \n</b>\nstr. 34 (krstni zapis \u0160tefana Podjavor\u0161ek)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1875\n</p><p>\n<b>\nPage: \n</b>\nstr. 34 (rojstvo mrtvorojene deklice Sel\u010dan)\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 35\n</p>",
"<p>\n<b>\nDate: \n</b>\n4 Jan 1791\n</p><p>\n<b>\nPage: \n</b>\nstr. 35, 1. zapis (krstni zapis Ga\u0161perja Kerhneja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 May 1832\n</p><p>\n<b>\nPage: \n</b>\nstr. 35, 6. vrstica (poro\u010dni zapis Bla\u017ea Stebleta in Marije Ahtig)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Nov 1819\n</p><p>\n<b>\nPage: \n</b>\nstr. 35; krstni zapis Marije Vrta\u010dnik (1819)\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Mar 1898\n</p><p>\n<b>\nPage: \n</b>\nstr. 352, 5. zapis (mrli\u0161ki zapis Matilde Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nVery High\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 36\n</p>",
"<p>\n<b>\nDate: \n</b>\n1841\n</p><p>\n<b>\nPage: \n</b>\nstr. 37 (poroka Luka Podgor\u0161ka in Jere Er\u0161aj)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 Nov 1876\n</p><p>\n<b>\nPage: \n</b>\nstr. 37, 3. zapis (por\u010dni list Franca Jan\u010darja Marije Strus)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 38\n</p><p>\n<b>\nConfidence: \n</b>\nVery High\n</p>",
"<p>\n<b>\nDate: \n</b>\n30 Sep 1806\n</p><p>\n<b>\nPage: \n</b>\nstr. 38, 18. zapis (krstni list Mihaela Omahna)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Feb 1805\n</p><p>\n<b>\nPage: \n</b>\nstr. 38, 3. vrstica (poro\u010dni zapis Simona Mayerja in Marije Kerhne)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n13 Mar 1898\n</p><p>\n<b>\nPage: \n</b>\nstr. 38, 5. vrstica (rojstni zapis Matilde Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Mar 1794\n</p><p>\n<b>\nPage: \n</b>\nstr. 38, 7. zapis (krstni zapis Jere Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n7 Feb 1774\n</p><p>\n<b>\nPage: \n</b>\nstr. 380 (poro\u010dni list Mihaela Podjavor\u0161ka in Lucije Kotnik)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 39\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Jul 1858\n</p><p>\n<b>\nPage: \n</b>\nstr. 39, 4. zapis (krstni zapis Margarete Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbefore 2006\n</p><p>\n<b>\nPage: \n</b>\nstr. 395\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 4\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Jan 1785\n</p><p>\n<b>\nPage: \n</b>\nstr. 4, 3. vrstica (krstni zapis Bla\u017ea Kerhneja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n17 Jan 1860\n</p><p>\n<b>\nPage: \n</b>\nstr. 4, 3. zapis (krstni zapis Antona Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 40\n</p>",
"<p>\n<b>\nDate: \n</b>\n1864\n</p><p>\n<b>\nPage: \n</b>\nstr. 40 (poro\u010dni zapis Matija Koglarja in Ne\u017ee Preklet)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n3 Feb 1809\n</p><p>\n<b>\nPage: \n</b>\nstr. 42 (Mrli\u0161ki list Jo\u017eefa Podjavor\u0161ka)\n</p>",
"<p>\n<b>\nDate: \n</b>\n20 Nov 1865\n</p><p>\n<b>\nPage: \n</b>\nstr. 43\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 Apr 1873\n</p><p>\n<b>\nPage: \n</b>\nstr. 43\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Jun 1776\n</p><p>\n<b>\nPage: \n</b>\nstr. 44 (krstni zapis Margarete Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n20 Feb 1792\n</p><p>\n<b>\nPage: \n</b>\nstr. 44 (poro\u010dni zapis Jurij \u017debovca in Jere Osel)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Apr 1806\n</p><p>\n<b>\nPage: \n</b>\nstr. 44, 4. zapis (krstni zapis Antona Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n14 Nov 1829\n</p><p>\n<b>\nPage: \n</b>\nstr. 44, 7. zapis (krstni list Andreja Habi\u010da)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n6 Apr 1896\n</p><p>\n<b>\nPage: \n</b>\nstr. 44; krstni zapis Marijane Debevec\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 45\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 45\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 46\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 46\n</p>",
"<p>\n<b>\nDate: \n</b>\n3 Mar 1899\n</p><p>\n<b>\nPage: \n</b>\nstr. 46, 1. zapis (krstni zapis Gregorja Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n12 Jul 1834\n</p><p>\n<b>\nPage: \n</b>\nstr. 46, 11. zapis (krstni list Magdalene Habi\u010d)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Feb 1878\n</p><p>\n<b>\nPage: \n</b>\nstr. 46, 3. zapis (poro\u010dni list Antona Omahna in Margarete Bratun)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 47\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 48\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 48\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Feb 1882\n</p><p>\n<b>\nPage: \n</b>\nstr. 48, 2. zapis (poro\u010dni zapis Petra Kotnika in Helene Ir\u0161i\u010d)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Aug 1836\n</p><p>\n<b>\nPage: \n</b>\nstr. 48, 5. zapis (krstni list Helene Jan\u010dar)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 49\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 49\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 5\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1823 and 1869\n</p><p>\n<b>\nPage: \n</b>\nstr. 5; Jurij Debevec - Polje 15\n</p>",
"<p>\n<b>\nDate: \n</b>\n24 Feb 1834\n</p><p>\n<b>\nPage: \n</b>\nstr. 50\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 50\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 51\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 51\n</p>",
"<p>\n<b>\nDate: \n</b>\n12 Nov 1807\n</p><p>\n<b>\nPage: \n</b>\nstr. 51, 5. vrstica (krstni zapis Andreja Mayerja\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 52\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 52\n</p>",
"<p>\n<b>\nDate: \n</b>\n1 Apr 1880\n</p><p>\n<b>\nPage: \n</b>\nstr. 52, 1. vrstica (krstni zapis Helene Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 53\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 53\n</p>",
"<p>\n<b>\nDate: \n</b>\n1831\n</p><p>\n<b>\nPage: \n</b>\nstr. 53 (krstni zapis Helene Nogra\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 54\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 54\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1955\n</p><p>\n<b>\nPage: \n</b>\nstr. 55\n</p>",
"<p>\n<b>\nDate: \n</b>\n27 Sep 1838\n</p><p>\n<b>\nPage: \n</b>\nstr. 55, 1. zapis (krstni list Franceta Jan\u010darja)\n</p>",
"<p>\n<b>\nDate: \n</b>\n23 Nov 1868\n</p><p>\n<b>\nPage: \n</b>\nstr. 55, 3. vrstica (poro\u010dni zapis Janeza Stebleta in Marije Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1955\n</p><p>\n<b>\nPage: \n</b>\nstr. 56\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Feb 1886\n</p><p>\n<b>\nPage: \n</b>\nstr. 56, 2. zapis (pro\u010dni list Marka Ljubi\u010da in Fran\u010di\u0161ke Habi\u010d)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Nov 1849\n</p><p>\n<b>\nPage: \n</b>\nstr. 56, 4. vrstica (mrli\u0161ki zapis Jo\u017eefa Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1955\n</p><p>\n<b>\nPage: \n</b>\nstr. 57\n</p>",
"<p>\n<b>\nDate: \n</b>\n1861\n</p><p>\n<b>\nPage: \n</b>\nstr. 57\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 57\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1995\n</p><p>\n<b>\nPage: \n</b>\nstr. 58\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 58\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 59\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Apr 1830\n</p><p>\n<b>\nPage: \n</b>\nstr. 59, 3. zapis (krstni list Antona Ljubi\u010da)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 6\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 6\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 6\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 6\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1823 and 1869\n</p><p>\n<b>\nPage: \n</b>\nstr. 6, 19. stavba (Stebl Sebastian, Bellipotok 3)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1827\n</p><p>\n<b>\nPage: \n</b>\nstr. 6, 2. zapis (Polle 25)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 6, stavba 98 (Otemna 12, Podgorschek Jakob)\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 6, stavbe 89 - 91 (Wresova 26, Mayer Simon)\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 6, stavbe 95 - 98 (Wresova 23, Kerehner Georg)\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 60\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 61\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 62\n</p>",
"<p>\n<b>\nDate: \n</b>\n5 Nov 1866\n</p><p>\n<b>\nPage: \n</b>\nstr. 62-63, 3. zapis (poro\u010dni list Janeza Jan\u010darja in Helene Jan\u010dar)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n14 Jan 1901\n</p><p>\n<b>\nPage: \n</b>\nstr. 62, 1. zapis (krstni zapis Pavline Pinter)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n2 Jul 1798\n</p><p>\n<b>\nPage: \n</b>\nstr. 62, 6. zapis (krstni zapis Ane Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 63\n</p>",
"<p>\n<b>\nDate: \n</b>\n2 Feb 1832\n</p><p>\n<b>\nPage: \n</b>\nstr. 63 (krstni zapis Matija Sel\u010dana)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Feb 1901\n</p><p>\n<b>\nPage: \n</b>\nstr. 63, 2. vrstica\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 64\n</p>",
"<p>\n<b>\nDate: \n</b>\n2 Oct 1863\n</p><p>\n<b>\nPage: \n</b>\nstr. 64 (krst Fran\u010di\u0161ka Pintra)\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 65\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 66\n</p>",
"<p>\n<b>\nDate: \n</b>\nJul 1895\n</p><p>\n<b>\nPage: \n</b>\nstr. 66 (krst Jakoba Gobca)\n</p>",
"<p>\n<b>\nDate: \n</b>\n14 Feb 1779\n</p><p>\n<b>\nPage: \n</b>\nstr. 66 (krstni zapis Matija Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n17 Jul 1901\n</p><p>\n<b>\nPage: \n</b>\nstr. 67, 2. zapis (krstni zapis Dominika Podjavor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n12 Feb 1855\n</p><p>\n<b>\nPage: \n</b>\nstr. 67, 3. vrstica (poro\u010dni zapis Valentina Goren\u0161ka in Agate Blazin\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 68\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 69\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Oct 1809\n</p><p>\n<b>\nPage: \n</b>\nstr. 69, 4. zapis (krstni zapis Ur\u0161ule Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 7\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 7\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1823 and 1869\n</p><p>\n<b>\nPage: \n</b>\nstr. 7, 2. stavba (Stebl Sebastian, Bellipotok 3)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 70\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 71\n</p>",
"<p>\n<b>\nDate: \n</b>\n1886\n</p><p>\n<b>\nPage: \n</b>\nstr. 71 (pogrebni zapis Helene Grilc)\n</p>",
"<p>\n<b>\nDate: \n</b>\n3 Feb 1858\n</p><p>\n<b>\nPage: \n</b>\nstr. 71 (poroka Matev\u017ea Mraka in Jere Podgor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 18 Dec 1801 and 25 Jan 1802\n</p><p>\n<b>\nPage: \n</b>\nstr. 717 (krstni zapis Marije Stepihar), 718\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 72\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Mar 1882\n</p><p>\n<b>\nPage: \n</b>\nstr. 73, 13. zapis (krstni list Apolonije Omahen)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n25 Dec 1800\n</p><p>\n<b>\nPage: \n</b>\nstr. 75, 1. zapis (krstni zapis Ne\u017ee Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n24 Jun 1853\n</p><p>\n<b>\nPage: \n</b>\nstr. 75, 8. zapis (krstni list Janeza Kon\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Jan 1853\n</p><p>\n<b>\nPage: \n</b>\nstr. 78; poro\u010dni zapis Matev\u017ea Podjavor\u0161ka in Marije Ram\u0161ak\n</p>",
"<p>\n<b>\nPage: \n</b>\nstr. 8\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 8, 4. lastnik (Bresova 23, Kerchne Gregor)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1891\n</p><p>\n<b>\nPage: \n</b>\nstr. 80 (poro\u010dni zapis Matija Sel\u010dana in Marije Lampret, ter Sebastijana Lampreta in Rozalije Iskra\u010d)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1864\n</p><p>\n<b>\nPage: \n</b>\nstr. 81\n</p>",
"<p>\n<b>\nDate: \n</b>\n31 Dec 1780\n</p><p>\n<b>\nPage: \n</b>\nstr. 82 (rojstni list Agnes Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n2 Sep 1879\n</p><p>\n<b>\nPage: \n</b>\nstr. 82, 12. zapis (krstni list Ur\u0161ule \u0160ircelj)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n12 Oct 1837\n</p><p>\n<b>\nPage: \n</b>\nstr. 82, 2. zapis (krstni list Terezije Selan)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n18 Mar 1903\n</p><p>\n<b>\nPage: \n</b>\nstr. 83, 1. vrstica (krstni zapis Jo\u017eefa Goren\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n24 Jun 1906\n</p><p>\n<b>\nPage: \n</b>\nstr. 83, 3. zapis (krstni list Janeza krstnika Jan\u010darja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Jan 1843\n</p><p>\n<b>\nPage: \n</b>\nstr. 83, 8. vrstica (krstni zapis Franca \u017debovca)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Jun 1901\n</p><p>\n<b>\nPage: \n</b>\nstr. 83; krstni zapis Fran\u010di\u0161ke Debevec\n</p>",
"<p>\n<b>\nDate: \n</b>\n1824\n</p><p>\n<b>\nPage: \n</b>\nstr. 84 (krstni zapis Jo\u017eefa Koro\u0161ca)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n17 Jul 1838\n</p><p>\n<b>\nPage: \n</b>\nstr. 85, 13. zapis (krstni list Jakoba \u0160irclja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1805\n</p><p>\n<b>\nPage: \n</b>\nstr. 86 (krstni zapis Marije \u0160kerjanc)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n19 Jan 1804\n</p><p>\n<b>\nPage: \n</b>\nstr. 86, vrstica 4 (krstni zapis Sebastijana Stebleta)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 May 1888\n</p><p>\n<b>\nPage: \n</b>\nstr. 87, 6. zapis (krstni zapis Ivane Ljubi\u010d)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n12 Jun 1842\n</p><p>\n<b>\nPage: \n</b>\nstr. 88, 2. vrstica (krstni zapis Antona Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nabout 1825\n</p><p>\n<b>\nPage: \n</b>\nstr. 9, 3. lastnik (Rosenberg 12, Podgorschegg Jakob)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n28 Sep 1865\n</p><p>\n<b>\nPage: \n</b>\nstr. 90, 2. zapis (krstni list Fran\u010di\u0161ke Habi\u010d)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 May 1904\n</p><p>\n<b>\nPage: \n</b>\nstr. 92, 4. zapis (krstni list Janeza Podjavor\u0161ka)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1828\n</p><p>\n<b>\nPage: \n</b>\nstr. 93 (krstni zapis Kunigunde Fijav\u017e)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n21 Nov 1812\n</p><p>\n<b>\nPage: \n</b>\nstr. 93, 3. zapis (krstni zapis Franca Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n11 Oct 1884\n</p><p>\n<b>\nPage: \n</b>\nstr. 94, 7. vrstica (mrli\u0161ki zapis Matev\u017ea Podgor\u0161ka)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n14 Feb 1814\n</p><p>\n<b>\nPage: \n</b>\nstr. 95, 3. vrstica (poro\u010dni zapis Andreja Blazin\u0161ka in  Apolonije Pirnat)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n8 Dec 1806\n</p><p>\n<b>\nPage: \n</b>\nstr. 95, 5. zapis (krstni zapis Toma\u017ea Stebleta)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1818\n</p><p>\n<b>\nPage: \n</b>\nstr. 952 (krstni zapis Andreja Pintarja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n17 Nov 1904\n</p><p>\n<b>\nPage: \n</b>\nstr. 96, 5. zapis (krstni zapis Fran\u010di\u0161ka Pinterja)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n1783\n</p><p>\n<b>\nPage: \n</b>\nstr. 98 (rojstni list Helene Podjavor\u0161ek)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\nMay 1903\n</p><p>\n<b>\nPage: \n</b>\nstr. 99; krstni zapis Angele Debevec\n</p>",
"<p>\n<b>\nDate: \n</b>\n14 May 1903\n</p><p>\n<b>\nPage: \n</b>\nstr. 99; Valentin \u017debovec je boter Mihu Kunstlju\n</p>",
"<p>\n<b>\nDate: \n</b>\n1868\n</p><p>\n<b>\nPage: \n</b>\nstr.106\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n13 Feb 1828\n</p><p>\n<b>\nPage: \n</b>\nstr.11, 8. zapis (poro\u010dni zapis Antona Ljubi\u010da in Gertrude Wokau)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n22 Apr 1860\n</p><p>\n<b>\nPage: \n</b>\nstr.31, 2. zapis (krstni list Markota Ljubi\u010da)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>",
"<p>\n<b>\nDate: \n</b>\n13 Feb 1796\n</p><p>\n<b>\nPage: \n</b>\ntr. 50, 2. zapis (krstni zapis Gertrude/Jere Steble)\n</p><p>\n<b>\nConfidence: \n</b>\nHigh\n</p>"
]
Dwr.ScriptLoaded('dwr_db_C_text_0.js');
