// This file is generated

C_note_0 = [
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://en.geneanet.org/cemetery/view/8388763\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nTranscript\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<strong></strong><span style=\"text-decoration:underline;\"><strong>Rodbina Angele in Dominika Podjavor\u0161ek</strong></span><strong></strong>\n</p>\n<p>\nFran\u010dek Pinter: iz Nove Cerkve se je poro\u010dil k \u0160teblet (Beli potok) in kasneje kupil Markovo doma\u010dijo<br />\n    +<br />\n    Helena<br />\n        Ton\u010dek<br />\n        *<a href=\"person.html?idx=697\">Angela</a><br />\n    +<br />\n    Germ: Dreno\u0161ekova iz Male Gore<br />\n        Pepi<br />\n        Radi<br />\n        Karli<br />\n        Ciril<br />\n        Dora<br />\n        Marica<br />\n        Metod<br />\n        Trezika<br />\n        An\u010dka\n</p>\n<p>\nprababica<br />\n    +<br />\n    Kotnik<br />\n        Tin\u010dek<br />\n        Helena<br />\n        _<br />\n    +<br />\n    Franc Podjavor\u0161ek: iz Doli\u010da se poro\u010di v Lipo<br />\n        *<a href=\"person.html?idx=711\">Dominik</a><br />\n        Janez Podjavor\u0161ek: poro\u010dil se je v Zre\u010de<br />\n            +<br />\n            Mima<br />\n                Marija Podjavor\u0161ek<br />\n                    +<br />\n                    Tone Hren<br />\n                        Marjan<br />\n                        Tone<br />\n                        Marta<br />\n                        Minka<br />\n                        Andrej<br />\n                Ivan Podjavor\u0161ek: umrl brez otrok<br />\n        Micika\n</p>\n<p>\n*<a href=\"person.html?idx=711\">Dominik Podjavor\u0161ek</a>: 17. 7. 1901<br />\n    + 29. 11. 1929<br />\n    *<a href=\"person.html?idx=697\">Angela Pinter</a>: 25. (3./)4. 1906\n</p>\n<p>\n        Katarina: 16. 11. 1930, gospodinja<br />\n            + 25. 11. 1957, kmalu sta se preselila v Velenje (Splitska 36, 3320 Velenje; 03 5861 668, 031 791 234)<br />\n            Jo\u017ee Pungartnik: 20. 2. 1929, upokojeni rudar\n</p>\n<p>\n                Toma\u017e Pungartnik: 25. 2. 1959, samostojni podjetnik<br />\n                    + 15. 10. 1988 (Ko\u017eeljskega 7, 3320 Velenje; 040 63 77 62, 03 897 72 83)<br />\n                    Jo\u017eica: 25. 10. 1965, frizerka<br />\n                        Dominik: 16. 6. 1989\n</p>\n<p>\n                Jo\u017eica: 21. 4. 1960, medicinska sestra<br />\n                    +<br />\n                        Lilijana: 13. 1. 1982, medicinska sestra<br />\n                            + 31. 5. 2003 (Zavr\u0161e 37, 2382 Mislinja; 02 88 56 366, 041 558 321)<br />\n                            Daniel Bla\u017ein\u010di\u010d: 19. 6. 1972, in\u017e. elek. vzdr.<br />\n                                [popadki na 20 minut]<br />\n                    + 18. 5. 2002 (Stanetova 11, 3320 Velenje; 040 699 217)<br />\n                    Andrej Kumer: 11. 9. 1972, zidar<br />\n                        Katarina: 30. 11. 1998\n</p>\n<p>\n                Andreja: 27. 11. 1966(/1967), prof. glasbe<br />\n                    + 5. 6. 1993 (\u0160alek 82, 3320 Velenje; 041 79 1234, 03 568 61 668)<br />\n                    Radivoj Mohori\u010d: 13. 1. 1964, arhitekt<br />\n                        Naja: 27. 11. 1996<br />\n                        Nace: 7. 4. 1994\n</p>\n<p>\n        Marija: 7. 11. 1931<br />\n            + poro\u010dila sta se in \u017eivita v Slov. Konjicah (\u0160olska ul. 16, Slov. Konjice; 03 575 42 96)<br />\n            Edi Laznik: 22. 4. 1927\n</p>\n<p>\n                Bo\u017eidar Laznik: 15. 5. 1958, industrijski oblikovalec<br />\n                    + (Gabrovnik)<br />\n                    Jelka: 20. 9. 1954, \u0161ivilja<br />\n                        Ur\u0161a: 30. 1. 1980, trgovka\n</p>\n<p>\n                Matja\u017e Laznik: 10. 11. 1965, trgovec<br />\n                    + (\u0160olska ulica 16, Slov. Konjice)<br />\n                    Elizabeta: 21. 6. 1971, kuharica<br />\n                        Jerneja: 4. 7. 1994\n</p>\n<p>\n        Dominik: 16. 6. 1933 - 1940 (umrl za davico, star 7 let, pokopan v Celju)\n</p>\n<p>\n        Cilka Podjavor\u0161ek<br />\n            +<br />\n            _<br />\n            +<br />\n            Vinko\n</p>\n<p>\n        Ivanka Podjavor\u0161ek: 29. 7. 1937, gospodinja, delavka<br />\n            + poro\u010dila sta se in \u017eivela pri Lopatjek<br />\n            Anton Sel\u010dan: 14. 1. 1933, tesar\n</p>\n<p>\n                Martin: 1959, nad. rud. teh.<br />\n                    + 27. 5. 1984 (Male Dole 46, 3213 Vojnik; 041 907 356)<br />\n                    Cveta: 3. 2. 1961<br />\n                        Lilijana: 3. 12. 1983, prodajalka<br />\n                            + (Trnovlje, Zagrad; 041 693 707)<br />\n                            Mitja: 1974<br />\n                                \u017dan: 18. 1. 2003<br />\n                        Doroteja: 17. 4. 1989\n</p>\n<p>\n                Jo\u017ee Sel\u010dan: 18. 3. (1961/)1960, hi\u0161nik<br />\n                    + [lo\u010dena?] (O\u0160 Petrov\u010de, Petrov\u010de 32; 041 783 277)<br />\n                    Zinka<br />\n                        Ga\u0161per: 18. 3. 1986\n</p>\n<p>\n                Du\u0161an: 4. 2. 1961, kova\u010d, kmetovalec<br />\n                    + 8. 9. 1984 (Lipa 24, 3213 Frankolovo; 03 57 74 632)<br />\n                    Irena: 14. 2. 1963, gospodinja<br />\n                        Klavdija: 10. 2. 1985, vrtnarski teh.<br />\n                        Ale\u0161: 15. 7. 1987, ra\u010dunal. teh.\n</p>\n<p>\n                Bernardka: 23. 6. 1964, kozmeti\u010darka<br />\n                    +<br />\n                        Sintja: 9. 4. 1985<br />\n                    + 22. 8. 1998 (Kajuhova 2, 3210 Slov. Konjice; 03 5754 192, 031 658 970)<br />\n                    Jo\u017ee Groblar: 21. 2. 1952, zobotehnik<br />\n                        Luka: 16. 7. 1996\n</p>\n<p>\n                Marko Sel\u010dan: 1971\n</p>\n<p>\n                Zvonka Sel\u010dan: 30. 1. 1976, poslovodja<br />\n                    + (Vine 2b, 3203 Nova Cerkev; 041 797 423)<br />\n                    Klemen Stropnik: 15. 8. 1976/1977, avtoprevoznik<br />\n                        Dominika: 20. 9. 2000<br />\n                        _\n</p>\n<p>\n        <a href=\"person.html?idx=699\">Anton Podjavor\u0161ek</a>: 27. 5. 1940, upokojeni mizar<br />\n            + 27. 9. 1963 (Lipa 19, 3213 Frankolovo; 03 5774490, 041 553 739)<br />\n            <a href=\"person.html?idx=691\">Anica</a>: 13. 5. 1944, gospodinja<br />\n                <br />\n                <a href=\"person.html?idx=704\">Boris Podjavor\u0161ek</a>: 15. 8. 1964 - ~1970 (umrl star 6 let v prometni nesre\u010di)<br />\n                <br />\n               <a href=\"person.html?idx=732\"> Jana</a>: 10. 1. 1967, dipl. \u017eiv. tehnolog; katehistinja, vodi delavnice molitve in \u017eivljenja, \u0161olo za animatorje ... (Lipa 19, 3213 Frankolovo; 031 527 989)<br />\n                <br />\n                <a href=\"person.html?idx=1162\">Mihelina</a>: 25. 5. 1972, dipl. agronom, del. terapevt<br />\n                    + 25. 5. 2002 (Zbiljska 1a, Medvode; 031 238 408)<br />\n                    <a href=\"person.html?idx=1139\">Iztok \u017debovec</a>: mag. teologije<br />\n                        <a href=\"person.html?idx=1129\">Filip</a>: 9. 4. 2003\n</p>\n<p>\n                <a href=\"person.html?idx=788\">Natalija</a>: 5. 7. 1974, prof. MA in FI, spec. zak. in dru\u017e. terapije<br />\n                    + 4. 9. 2004 (041 319 027)<br />\n                    <a href=\"person.html?idx=782\">Matja\u017e Kon\u010dar</a>: dipl. ing. elekt.\n</p>\n<p>\n                <a href=\"person.html?idx=705\">Boris Podjavor\u0161ek</a>: 26. 7. 1975, mizar<br />\n                    + (Lipa 19, 3213 Frankolovo; 03 5774 490, 041 974 062)<br />\n                    <a href=\"person.html?idx=98\">Lidija Buri\u010d</a>: 10. 6. 1976, trgovka<br />\n                        <a href=\"person.html?idx=97\">Borut</a>: 8. 1. 1996\n</p>\n<p>\n        Valentin Podjavor\u0161ek: 29. 1. 1942, upokojeni mizar<br />\n            + 1. 6. 1968 (Frankolovo 14h, 3213 Frankolovo; 03 5774 524)<br />\n            Ivanka: 22. 8. 1947, upokojeni gost. tehnik\n</p>\n<p>\n                Aleksander Podjavor\u0161ek: 26. 12. 1968, mizar<br />\n                    + (Frankolovo 14 h, 3213 Frankolovo)<br />\n                        Alja\u017e: 16. 6. 2000\n</p>\n<p>\n                Romana: 21. 6. 1973, ekon. tehnik<br />\n                    + 10. 5. 2003 (03 54 82 455)<br />\n                    Vekoslav Jurina: ra\u010dunalni\u010dar<br />\n                        Timeja: 21. 10. 2003\n</p>\n<p>\n        <a href=\"person.html?idx=750\">Konrad Podjavor\u0161ek</a><br />\n            + poro\u010dila sta se in \u017eivita v \u0160martnem (Brezova 14, 3201 \u0160martno v Ro\u017eni dolini)<br />\n                Peter: 1975\n</p>\n<p>\n        Angela: 10. 6. 1945<br />\n            + (Pristava 3, 8774 Raka pri Kr\u0161kem)<br />\n            Slavko Lu\u017enik<br />\n                Darja: 24. 2. 1967<br />\n                    +<br />\n                        Ines: 1986<br />\n                        Natja: 1983<br />\n                    + (Nem\u010dija)<br />\n            + 7. 7. 1970<br />\n            Ivan Grm: 14. 3. 1939<br />\n                Robert: 21. 2. 1972\n</p>\n<p>\n        <a href=\"person.html?idx=771\">Marko Podjavor\u0161ek</a>: 27. 4. 1947 - 1967 (umrl v prometni nesre\u010di, star 19 let)\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://en.geneanet.org/cemetery/view/11361226\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://en.geneanet.org/cemetery/view/11361082\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://en.geneanet.org/cemetery/view/11361200\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://en.geneanet.org/cemetery/view/9679124\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://en.geneanet.org/cemetery/view/12135510\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nTranscript\n</i>\n<div class=\"grampsstylednote\">\n<p>\n79604032\n</p>\n<p>\nLast Name: PODJAVORSEK<br />\nFirst Name: ALBERT<br />\nMaiden Name:<br />\nPlace of Birth: SPOD.DOLIC<br />\nDate of Birth: 03/31/1933<br />\nPrisoner #:\n</p>\n</div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/search/person/79604032\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79604033\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79605365\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/zrece/04784/?pg=105\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79604034\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79605366\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79604035\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79605367\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79604036\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79605368\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79604037\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79605369\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79604038\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79605370\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/document/79604039\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nTranscript\n</i>\n<div class=\"grampsstylednote\">\n<p>\nDru\u017eina Borovnik\n</p>\n<p>\nListe Nr. 28-I\n</p>\n<p>\n\u00fcber die Aussiedlung am 22. Avgust 1941 in Reichenburg\n</p>\n<p>\nBorovnik Heinrich 3. 7. 1889, Sternstein 29; umrl 1962\n</p>\n<p>\nKatharina, geb. Goren\u0161ek \u2013 1893; umrla 1972\n</p>\n<p>\nHeinrich 13. 4. 1915 \u2013 Lipa 29, Frankolovo, knjigovezec, upokojenec\n</p>\n<p>\nBartholomeus 20. 8. 1922 \u2013 \u0160entjurij, ing. agronomije, upokojenec\n</p>\n<p>\nMartin 29. 11. 1925 \u2013 Lipa 29, Frankolovo, gospodar\n</p>\n<p>\nChristina 31. 5. 1931 \u2013 Lipa 29, Frankolovo \u2013 neporo\u010dena\n</p>\n<p>\nVinzenz 14. 7. 1932 \u2013 Vodice pri Ljubljani, u\u010ditelj, upokojenec\n</p>\n<p>\nKatharina 13. 4. 1934 \u2013 por. Pinter v Mariboru\n</p>\n<p>\nJohann 25. 5. 1936 \u2013 Celje, UI. frankolovskih \u017ertev\n</p>\n<p>\nTerezija 1916 \u2013 Bjelovar, poro\u010dena\n</p>\n<p>\nValentin 1921 \u2013 socialni delavec, umrl 12. 2. 1966\n</p>\n<p>\nEmil 1924 \u2013 Lipa 29, Frankolovo\n</p>\n<p>\nJo\u017eica 1927 \u2013 por. \u0160afran, Zagreb \u2013 Olovska 19\n</p>\n<p>\nAnica 1928 \u2013 por. Del\u010dnjak, Trnovlje \u2013 kmetica\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00572/?pg=21\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=121\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00515/?pg=22\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04053/?pg=23\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01926/?pg=4\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00645/?pg=6\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01770/?pg=158\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/javor/00648/?pg=2\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/zrece/04676/?pg=10\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/5292/?pg=16\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00637/?pg=11\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01918/?pg=11\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/javor/00647/?pg=105\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02808/?pg=14\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/04378/?pg=107\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04044/?pg=106\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=106\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/04378/?pg=109\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=109\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01788/?pg=12\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04044/?pg=11\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01927/?pg=14\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04042/?pg=11\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02808/?pg=21\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/04378/?pg=115\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04129/?pg=58\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/00218/?pg=115\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02808/?pg=25\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/5289/?pg=118\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00583/?pg=117\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01927/?pg=15\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=120\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02808/?pg=33\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/03784/?pg=127\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04044/?pg=127\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/5289/?pg=132\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00510/?pg=69\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/vodice/02812/?pg=16\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/vojnik/04497/?pg=14\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/04406/?pg=135\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01784/?pg=68\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=139\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/5292/?pg=153\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/vojnik/04476/?pg=139\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/04378/?pg=15\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01788/?pg=141\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01767/?pg=36\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04058/?pg=74\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04041/?pg=75\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04041/?pg=75\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01773/?pg=152\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/vitanje/04460/?pg=78\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00579/?pg=78\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00510/?pg=96\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00573/?pg=156\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/vodice/02810/?pg=83\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01923/?pg=17\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04041/?pg=81\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04041/?pg=83\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04058/?pg=84\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/00573/?pg=167\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=16\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02808/?pg=87\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/04406/?pg=21\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/vodice/02809/?pg=19\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/00583/?pg=182\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/00574/?pg=184\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/5292/?pg=25\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/javor/00646/?pg=21\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01773/?pg=190\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00644/?pg=3\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00583/?pg=3\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/03788/?pg=21\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01918/?pg=21\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00573/?pg=20\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=21\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00518/?pg=23\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/stanga/03416/?pg=24\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00574/?pg=24\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04128/?pg=125\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04130/?pg=25\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00571/?pg=26\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01913/?pg=264\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04128/?pg=134\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04054/?pg=14\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=28\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/stanga/04289/?pg=29\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/03789/?pg=30\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/00240/?pg=30\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01927/?pg=32\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01916/?pg=18\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/vojnik/04475/?pg=29\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://collections.arolsen-archives.org/en/archive/3-1-3-2_1697000\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00636/?pg=4\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nReport\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/javor/03857/?pg=4\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00582/?pg=4\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02814/?pg=32\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01924/?pg=31\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/04406/?pg=33\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/5292/?pg=37\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/00579/?pg=160\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/00579/?pg=160\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00645/?pg=18\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00637/?pg=34\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04058/?pg=18\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/polica/01768/?pg=34\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01916/?pg=21\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04129/?pg=18\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01775/?pg=34\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04042/?pg=35\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/vojnik/04497/?pg=36\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00579/?pg=177\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/vodice/02812/?pg=40\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00645/?pg=38\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01916/?pg=24\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04058/?pg=21\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/5292/?pg=44\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00571/?pg=38\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/vitanje/04460/?pg=192\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=38\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04042/?pg=4\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01774/?pg=4\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/03789/?pg=41\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00515/?pg=22\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://img.data.matricula-online.eu/image/aHR0cDovL2hvc3RlZC1pbWFnZXMubWF0cmljdWxhLW9ubGluZS5ldS9pbWFnZXMvbWF0cmljdWxhL1NJLUxOU0EvbWF0cmljdWxhL1ZvZGljZS9LcnN0bmUlMjBrbmppZ2UvUiUyMFZvZGljZSUyMDE4NTQtMTg5MC9SJTIwVm9kaWNlJTIwMTg1NC0xODkwX1N0cmFuXzA0NS5qcGc/?csrf=o6ye7DIkLtpggXHjqD3Ejk0oc0GhLg6c0OQAVaVVrPYLjnwKtxyLdJuaIdc6MZNr&amp;ctrl=46ee78d0254238fb841ec932464ec3a9\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://img.data.matricula-online.eu/image/aHR0cDovL2hvc3RlZC1pbWFnZXMubWF0cmljdWxhLW9ubGluZS5ldS9pbWFnZXMvbWF0cmljdWxhL1NJLUxOU0EvbWF0cmljdWxhL1ZlbGVzb3ZvL0tyc3RuZSUyMGtuamlnZS9SJTIwVmVsZXNvdm8lMjAxODYxLTE4ODcvUiUyMFZlbGVzb3ZvJTIwMTg2MS0xODg3LTAwNDcuanBn/?csrf=o6ye7DIkLtpggXHjqD3Ejk0oc0GhLg6c0OQAVaVVrPYLjnwKtxyLdJuaIdc6MZNr&amp;ctrl=0c959110ae561346ba10896c6ae49f7a\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04129/?pg=23\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=44\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/javor/00646/?pg=46\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/04406/?pg=47\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/5292/?pg=52\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/javor/00646/?pg=48\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01927/?pg=49\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/vitanje/04465/?pg=49\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00637/?pg=49\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=51\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/vojnik/04480/?pg=52\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/tunjice/02667/?pg=54\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00637/?pg=56\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04059/?pg=56\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01927/?pg=59\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00516/?pg=44\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=56\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01917/?pg=60\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/00645/?pg=32\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/5292/?pg=68\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00571/?pg=62\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01772/?pg=63\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/5292/?pg=69\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01774/?pg=64\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04129/?pg=34\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/5292/?pg=73\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01789/?pg=68\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=69\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/03788/?pg=72\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/vodice/02812/?pg=74\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nResearch\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01770/?pg=116\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01918/?pg=74\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00572/?pg=5\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/stanga/03417/?pg=76\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01790/?pg=82\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=80\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04129/?pg=42\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/polica/01769/?pg=84\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01917/?pg=83\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/5292/?pg=91\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/jance/04378/?pg=84\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/02795/?pg=84\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/04406/?pg=86\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02807/?pg=84\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/polica/01768/?pg=86\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/cerklje-na-gorenjskem/00218/?pg=87\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01918/?pg=88\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04044/?pg=88\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/javor/00646/?pg=92\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/5292/?pg=100\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/stranice/02808/?pg=3\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04043/?pg=93\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/smartno-v-rozni-dolini/04054/?pg=48\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01788/?pg=96\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00572/?pg=25\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/nova-cerkev/01771/?pg=95\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/frankolovo/5292/?pg=104\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/st-ilj-pod-turjakom/04129/?pg=50\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/04406/?pg=103\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/ljubljana/vodice/04406/?pg=103\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/maribor/dolic/00511/?pg=105\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nCitation\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01927/?pg=14\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/en/slovenia/ljubljana/prezganje/01918/?pg=32\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\nhttps://data.matricula-online.eu/sl/slovenia/maribor/frankolovo/00571/?pg=50\n</p>\n</div>\n</div>"
]
Dwr.ScriptLoaded('dwr_db_C_note_0.js');
